### ISSUE TITLE
KEY=0 value is not "0"

### ISSUE THREAD

**Issue by gokure** [vlucas/phpdotenv#100]
Hi,
```
# .env config file

KEY=0 # ""
KEY="0" # "0"
```
The number zero `0` (not quoted) should assert to blank `""`, this is the bug or feature?

**Comment by GrahamCampbell** [comment]
> The number zero 0 (not quoted) should assert to blank ""

Why would it?

**Comment by gokure** [comment]
Sorry my pool English.

It is not "assert", is "got".

I got blank string `""` rather than string `"0"`  if I set `KEY=0`, this is bug or feature?

**Comment by gokure** [comment]
I'm sorry, This is different version, Laravel used old version of dotenv.

**Comment by GrahamCampbell** [comment]
Try convincing Taylor to upgrade. :)
