### ISSUE TITLE
Validation is impossible in 2.0 release without explicitly loading .env from disk

### ISSUE THREAD

**Issue by nirvana-msu** [vlucas/phpdotenv#101]
Previous version allowed to perform validation without having to load `.env` file from disk, which is very useful for production set-up, e.g. as discussed [here](https://github.com/vlucas/phpdotenv/issues/63#issuecomment-89490588):

```php
// Load required environment variables from .env in development
$dotenv = new Dotenv\Dotenv();
if(BULLET_ENV == 'development') {
    $dotenv->load(dirname(__DIR__), 'dev.env');
}
// Required ENV vars for this app in production
$dotenv->required([
    'DATABASE_URL',
    'PATH_FILE_UPLOADS',
    'GOOGLE_PLACES_API_KEY',
    'RAVEN_DSN',
    'MANDRILL_USER', 'MANDRILL_PASS'
]);
```

However if you try to do the same with latest release (directory should now be specified in `Dotenv` constructor rather than `load`method, but this is minor), PHP will throw an exception because it tries to initialize `Validator` by passing in `loader` which is `null`. That practically makes it impossible to use validation in production.. why was it done? How can I do validation without loading `.env`?
```
PHP Catchable fatal error:  Argument 2 passed to Dotenv\\Validator::__construct() must be an instance of Dotenv\\Loader, null given, called in /var/www/example.com/vendor/vlucas/phpdotenv/src/Dotenv.php on line 83 and defined in /var/www/example.com/vendor/vlucas/phpdotenv/src/Validator.php on line 34
```

**Comment by vlucas** [comment]
I will do some experimentation around this for a new release. I definitely want to be able to still have validation without loading a physical .env file.
