### ISSUE TITLE
Update .env from php

### ISSUE THREAD

**Issue by auro1** [vlucas/phpdotenv#105]
Is there any way to actually update the .env file from PHP? I would use this to automatically update passwords from a cronjob.

**Comment by xjchengo** [comment]
You can try this way:
```
function env_replace($pattern , $replacement , $envFilename, $limit = -1, &$count = null)
{
    $subject = file_get_contents($envFilename);
    $subject = preg_replace($pattern, $replacement, $subject, $limit, $count);
    if ($subject === null) {
        return null;
    }
    return file_put_contents($envFilename, $subject);
}

env_replace('/oldpassword/', 'newpassword', '.env');
```

**Comment by vlucas** [comment]
This is not the point of phpdotenv. It was never meant to be used in production - it only _emulates_ environment variables being set for local development and testing. In production, you should be using *real* environment variables set via Apache/Nginx configuration, etc.
