### ISSUE TITLE
$_ENV empty but $_SERVER and getenv() working

### ISSUE THREAD

**Issue by Muffinman** [vlucas/phpdotenv#108]
Hi, I recently ran into this problem where the $_ENV array isn't filled when trying to exec() another script. For example:

`index.php` contents:
```
<?php

# Get the server's env vars
require 'vendor/autoload.php';
$dotenv = new Dotenv\Dotenv('/etc/myconfigdir');
$dotenv->load();

var_dump($_ENV); // Correctly outputs a full array
var_dump($_SERVER); // Correctly outputs a full array

$result = exec('/usr/bin/php ' . dirname(__DIR__) . '/test.php');
```

`test.php` contents:
```
<?php

# Get the server's env vars
require 'vendor/autoload.php';
$dotenv = new Dotenv\Dotenv('/etc/myconfigdir');
$dotenv->load();

var_dump($_ENV); // EMPTY!?
var_dump($_SERVER); // Correctly outputs a full array
```

I'm assuming this has something to do with the exec'd PHP script not being run from a valid shell? Is this normal?

**Comment by xjchengo** [comment]
You can see this `http://php.net/manual/en/reserved.variables.environment.php#98113` to handle it.

**Comment by Muffinman** [comment]
Thanks, that worked! For others with this issue:

Setting `variables_order = "EGPCS"` in my php.ini fixed the issue for me.
