### ISSUE TITLE
Certain variables not being loaded

### ISSUE THREAD

**Issue by Juddling** [vlucas/phpdotenv#109]
For some reason when Laravel calls `Dotenv::load()`, the skip on the following line is being called for just four of my .env variables: `DB_HOST`, `DB_USERNAME`, `DB_PASSWORD`, `DB_NAME`

This is the skip stopping the variable being loaded into `$_ENV`
https://github.com/vlucas/phpdotenv/blob/1.1/src/Dotenv.php#L83

After calling the load method, if I call `print_r( $_ENV )` these four values aren't present.

This only happens intermittently, for most requests there is no issue.

The host contains dots and the password contains a quote (not at the beginning or end), I doubt this is causing the issue but I thought I'd mention it.

BEFORE calling load, I can get these values using `getenv()` even though they aren't present in `$_ENV` or `$_SERVER`.

I'm using PHP 5.6.8 on windows through XAMPP 3.2.1

**Comment by chrisabrams** [comment]
I'm also having a very similar issue.

**Comment by jshah4517** [comment]
Same issue here, Windows 8, EasyPHP with PHP 5.6.4. Doesn't appear to be happening on Mac OS X.

**Comment by nebulousGirl** [comment]
+1

Any idea on what might cause the issue?

**Comment by coatesap** [comment]
+1 

Experiencing intermittent loading of environment variables on Windows 10, WAMP, PHP 5.4. Works probably 99% of the time, then fails on the 1%. Am using $_ENV.

**Comment by GrahamCampbell** [comment]
https://github.com/vlucas/phpdotenv/issues/76#issuecomment-167806230
