### ISSUE TITLE
getting all variables but not database host

### ISSUE THREAD

**Issue by frsechet** [vlucas/phpdotenv#112]
Hi,

I'm using docker for my development environment for a bedrock project (https://roots.io/bedrock/). I correctly linked my database container with my webserver container as many other local websites (on various frameworks) are accessing it flawlessly (the alias is simply "db" usually in the .env file).

However, with bedrock, just cloned from the bedrock repo, I get the following error: "We were able to connect to the database server (which means your username and password is okay) but not able to select the /docker_web_1/db database."

My .env file however states:

    DB_NAME=bedrock
    DB_USER=user
    DB_PASSWORD=user
    DB_HOST=db

Of course, the "bedrock" database, the username, password and host do exist, but for some reason it seems that bedrock is trying to load a db called "/docker_web_1/db" ("docker_web_1" is the name of the webserver container, "db" is the host of the database - the database is supposed to be called "bedrock"). It seems the DB_NAME is ignored and replaced with other parameters.
A "normal" install of wordpress with the same environment and parameters works perfectly.

I got bedrock to work changing this single line here and manually defining the DB_NAME, which seems to indicate that the issue comes from phpdotenv: https://github.com/roots/bedrock/blob/master/config/application.php#L42

How can I fix this?

Thanks!

**Comment by frsechet** [comment]
Nevermind, I found the issue. It seems that my container was setting DB_NAME (but nothing else). Changing this variable to DB_BANANA fixed it. Less clear but works the same... :-)

**Comment by vlucas** [comment]
Glad you were able to resolve this. :+1:
