### ISSUE TITLE
Simultaneous requests on Windows server don't write to $_ENV or $_SERVER

### ISSUE THREAD

**Issue by baerwolf1983** [vlucas/phpdotenv#119]
Simultaneous requests on Windows servers will lead to `findEnvironmentVariable` returning the value set by the first request.
Because this:
```php
$value = getenv($name);
return $value === false ? null : $value; // switch getenv default to null
```
returns a non-null value, neither `$_ENV` nor `$_SERVER` will get populated by `setEnvironmentVariable`.

Currently I bypass this issue by setting immutable to false.

**Comment by jshah4517** [comment]
Related to issue #109, changing the immutable variable to false does appear to stop the problems experienced currently as a temporary measure.
