### ISSUE TITLE
Confusing Docs or alternative instantation

### ISSUE THREAD

**Issue by jhmilan** [vlucas/phpdotenv#120]
Using phpdoenv 1.1.1. (this is the version in my composer.lock after requiring "vlucas/phpdotenv": "~1.0")

I tried this as per the README:

```
$dotenv = new Dotenv\Dotenv(__DIR__.'/..');
$dotenv->load();
```

I got an fatal error "Dotenv\Dotenv" not found. Looking into the guts of Laravel 5 to see how it instantiate it I got it running by just:

```
Dotenv::load(__DIR__ . '/..');
```
 
I wonder if is something that has changed or I'm missing some configuration in my composer.json around autoload. It would be great it the docs brought some more light around this (autoloading options)

**Comment by tuupola** [comment]
[README for 1.1]( https://github.com/vlucas/phpdotenv/tree/1.1) suggests:

```php
Dotenv::load(__DIR__);
```

[README for 2.0](https://github.com/vlucas/phpdotenv/tree/2.0) says: 

```php
$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();
```

**Comment by jhmilan** [comment]
My bad, sorry. I didn't realize about the 2.* release on May since I'm using 1.*

https://github.com/vlucas/phpdotenv shows the readme for the 2.0 what confused me.

Thanks @tuupola. Closing
