### ISSUE TITLE
Parse Environment variables to PHP Data Types

### ISSUE THREAD

**Issue by jpcercal** [vlucas/phpdotenv#121]
Dear @vlucas,

I wrote a library to get values from environment variables and parse to the PHP data types, do you could put my library as an option to read data in your README file?

I mentioned your library in my repository too https://github.com/jpcercal/environment.

My library is 100% covered by php unit tests. =)

Thanks guy!

**Comment by GrahamCampbell** [comment]
Please see the other discussions. We just expect other tools to wrap this as they please.
