### ISSUE TITLE
return type of Loader::__construct & Loader::load

### ISSUE THREAD

**Issue by alcohol** [vlucas/phpdotenv#123]
Just wondering if there is a particular reason you went with `void` there? Since technically it actually returns an instance of `self` (or `Loader`). Confuses some IDE's right now. Same with `load`, returns `$lines` which can be an array, but is docblocked as `void` too.

**Comment by GrahamCampbell** [comment]
> Since technically it actually returns an instance of self (or Loader).

No it doesn't....

**Comment by GrahamCampbell** [comment]
> Confuses some IDE's right now.

Yeh, phpstorm is just wrong here. Really annoys me. I blame java developers.

**Comment by alcohol** [comment]
Okay, but what about `Loader::load`? Or should I have opened two separate issues?
