### ISSUE TITLE
2.0 Changelog / Upgrade note?

### ISSUE THREAD

**Issue by Soullivaneuh** [vlucas/phpdotenv#125]
Where is the changelog?

Has 2.0 some BC break? This should be noted somewhere.

Thanks.

**Comment by GrahamCampbell** [comment]
Sorry, no change log.

**Comment by Soullivaneuh** [comment]
At least, could you tell me the risks to upgrade from 1.x to 2.x?

**Comment by GrahamCampbell** [comment]
If I could remember, sure, lol. :)

**Comment by GrahamCampbell** [comment]
If you're using only the basic features from 1.x, I think you should be totally fine upgrading.

**Comment by Soullivaneuh** [comment]
What do you mean by "only the basic features"? That is a little bit scary. :-P

I'll try it, thanks.

**Comment by GrahamCampbell** [comment]
What I'm meaning is that you'll need to be careful with the edge cases. ;)
