### ISSUE TITLE
A '0' environment variable value turns into an empty string

### ISSUE THREAD

**Issue by TheOnlyMerlin** [vlucas/phpdotenv#126]
I am working in Laravel and I was trying to track down an odd issue, and noticed that an environment variable I set as =0 was coming back as ''. I was doing math on the value, so it was important that the value be a numeral.  Additionally, this was very unexpected behavior.

The culprit seems to be this line in the  method Dotenv.php (v1.x) 

```php
    protected static function sanitiseVariableValue($value)
    {
        $value = trim($value);
        if (!$value) {
            return ''; // the culprit
        }
        // ...
    }
```

Note this appears to be fixed in the equivalent method in 2.0.

I'm guessing this isn't likely to be fixed in 1.0? 

I haven't looked too deeply into how I would fix this, but would a PR be considered, or is it one of those situations where unwanted behavior is now possibly being relied upon ([xkcd: Workflow](https://xkcd.com/1172/))?

Or would I have better chances trying to convince Laravel to use 2.x?

**Comment by stephenorr** [comment]
@TheOnlyMerlin Did you ever get an answer to this?

**Comment by GrahamCampbell** [comment]
Laravel uses 2.x.
