### ISSUE TITLE
Providing example file for package.

### ISSUE THREAD

**Issue by rquadling** [vlucas/phpdotenv#127]
Hi.

I'm going to use ``vlucas/phpdotenv`` for one of my packages.

I'd like to create an ``mypackage.dotenv.example`` file and have that installed into the root of the user's project (i.e. parallel to ``vendor`` rather than embedded within it).

Is this possible?

I suspect this is more of a composer issue, but I was wondering how packages that use ``vlucas/phpdotenv`` provide the example file for the users of their package.

It could be possible to say that the example file is tucked away in vendor, but ideally, I'd like to leave vendor alone and provide the example file in another location, allowing the developer who incorporates my package to not have to go hunting for the example file.

**Comment by vlucas** [comment]
I am not sure how to do this, other than providing written steps to do this in your package's installation instructions.

**Comment by rquadling** [comment]
Which is what we are doing. Also, I wasn't aware that only 1 .env file is possible. I suppose it makes sense, but it would be nice to be able to keep .env files for different packages separate.
Unless I've missed something.
