### ISSUE TITLE
Throw exception on required() if loader is still not set

### ISSUE THREAD

**Issue by staelche** [vlucas/phpdotenv#128]
Hi,

I stumbled across a small issue which could be solved a little bit nicer.

```
$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->required('SOMETHING');
$dotenv->load();
```

The code leads to a fatal error that the loader is null when passing it into the validator. I had to look into the sources to see that I need to execute the required() method after loading the file. At first I expected you are collecting a list of validation rules you will check against during load (Best solution, as per my oppinion).

But already throwing an exception with a proper error message communicating the misuse of the library would be an improvement. 

Plus you could enhance the documentation to show the instantiation and load() before calling the required() method in the sample.

Anyway, a nice and very useful library!

Thomas

**Comment by vlucas** [comment]
This behavior will be changed very soon to allow variable checking before loading a file, as it was in 1.x.

**Comment by vlucas** [comment]
Looking at this issue, it seems like the published version is just out of date. I added a test for this scenario, and it passes on `master`. I will merge the test in, and then release a new version.
