### ISSUE TITLE
PHP >= 5.3.9?

### ISSUE THREAD

**Issue by RinkAttendant6** [vlucas/phpdotenv#131]
The [diff between versions 2.0.1 and 2.1.0](https://github.com/vlucas/phpdotenv/compare/v2.0.1...v2.1.0) show that the minimum required PHP version has been upped to 5.3.9. It seems to be have been done explicitly in 1f207799d61a7d0fc50dfcedbe0ecf350a770af4.

Any reason for this new requirement?

**Comment by GrahamCampbell** [comment]
We do not feel that we should support such old versions of php anymore. You are of course free to use 2.0.x if you really need old php version support. If it were really up to me, I'd drop all php versions that are EOL, so we'd bump to 5.5.+.

**Comment by RinkAttendant6** [comment]
Thanks for the response. I'd love to upgrade my application to PHP 5.5+ too but unfortunately the IT department only provides servers with PHP 5.3.2 at the time :( Guess I'll stick to 2.0.x for now.

**Comment by GrahamCampbell** [comment]
Well, you should really get them to at least upgrade to the latest 5.3.x. If you are processing sensitive user data, then your users are at risk.
