### ISSUE TITLE
Discovering correct directory for .env file from composed package perspective.

### ISSUE THREAD

**Issue by rquadling** [vlucas/phpdotenv#132]
Hi.

So I'm using phpdotenv in a package that my team will compose into their projects.

I don't know their setups, but I need to be able to locate the directory containing the .env file.

I assume it is a hardcoded set of ``dirname(__DIR__)`` locally and ``dirname(dirname(dirname(__DIR__)))`` (I think it is 3) for live.

**Comment by GrahamCampbell** [comment]
You can set the directory you want to use.
