### ISSUE TITLE
Why is it required to have envvars with spaces to be surrounded by quotes?

### ISSUE THREAD

**Issue by rquadling** [vlucas/phpdotenv#133]
Hi.

I can set an envvar at the command line without quotes.

```
set a
set a=1 2 3
set a
set a=
```

shows
```
[ 2015/10/30 16:12:29 ] [ D:\Scratch ] >set a
ALLUSERSPROFILE=C:\ProgramData
ANSICON=260x9999 (260x81)
ANSICON_DEF=7

[ 2015/10/30 16:12:30 ] [ D:\Scratch ] >set a=1 2 3

[ 2015/10/30 16:12:30 ] [ D:\Scratch ] >set a
a=1 2 3
ALLUSERSPROFILE=C:\ProgramData
ANSICON=260x9999 (260x81)
ANSICON_DEF=7

[ 2015/10/30 16:12:30 ] [ D:\Scratch ] >set a=

```

So no need to force quotes.

The issue is that I now have to remove quotes because I've got spaces from the env because they need to be present in the ```.env``` file.

And if we want to keep quotes, we have to escape them too.

This is going back to the nightmare of ```magic_quotes``` and all the hassle that gives.

**Comment by GrahamCampbell** [comment]
I don't really agree here to be totally honest, sorry.

**Comment by rquadling** [comment]
Using quotes around string with spaces when not required results in additional work to remove them. But how do you know if you have to remove them?

Say the string you want to store is ```"Top quality sales"```. To set this as a normal env I can use ...

```set HEADING="Top quality sales"```

But to get this into a .env file I have to ...

```HEADING="\"Top quality sales\""```

Which is terrible. PHP4 +  magic_quotes is back!

env vars are literals. No escaping necessary.

As a consequence of having to quote them, by the time the var is in PHP, it has these redundant quotes. Single or double, depends upon the user, not me as a dev.

I suppose the other way of looking at this is what is so special about a space in the string that it requires escaping? The only thing I can think of is if you want to include leading/trailing whitespace.

**Comment by tuupola** [comment]
If values contain special characters which have a special meaning to shell then value should be quoted or escaped. Both space and " have a special meaning to shell. Current behaviour follows POSIX shell behaviour and should be considered correct.

**Comment by rquadling** [comment]
Annoying "feature". Grumble grumble.

**Comment by damian-pf** [comment]
> If values contain special characters which have a special meaning to shell then value should be quoted or escaped

@tuupola Does this mean that we also cannot wrap the value in quotes for the user?

**Comment by tuupola** [comment]
@damian-pf I do not understand the question. Can you show an example?

**Comment by damian-pf** [comment]
@tuupola Like this

https://github.com/damian-pf/phpdotenv/commit/735c2e19325f3c42a0dab3c73c852e566b3b36da

This way we wrap it in quotes and the user is free to leave them out.
I can understand that we may want to force the user to use good standards.

Do you see any issues with this solution?
