### ISSUE TITLE
Overloading loader in Dotenv\Dotenv class

### ISSUE THREAD

**Issue by pinepain** [vlucas/phpdotenv#136]
It looks a bit inconsistent, probably, result of refactoring, but there are loader created in  both `Dotenv::__constructor()` and `Dotenv::load()` methods with same signature. I understand that loader object may be changed in `Dotenv::overload()` and loader itself required in `Dotenv::required()`.

While it is a bit trivial, it may be solved in a few ways:
 - Create local `muatable_loader` in `Dotenv::overload()` and do not override class loader.
 - Pass `immutable` flag be`\Dotenv\Loader::load()` method to override existent `immutable` setting in loader.

**Comment by alexw23** [comment]
Would also be good to be able to pass which fields can be overridden (as an array). I have an instance where I only want to allow overriding of a few fields.

**Comment by GrahamCampbell** [comment]
I think this was addressed. Feel free to PR any changes if you want them.
