### ISSUE TITLE
Username error while trying to fetch data from file

### ISSUE THREAD

**Issue by ssi-anik** [vlucas/phpdotenv#137]
I was doing everything as documented. But when I tried getting getenv('username') which is enlisted in the .env file but I get my local pc username. what is wrong? Was I doing anything wrong?
![screenshot_30](https://cloud.githubusercontent.com/assets/2676602/11199286/6ee8b376-8cf6-11e5-823a-66e95b6a7af7.png)

**Comment by rquadling** [comment]
The ``username`` is already defined as an environment variable. If you want to override it based upon your ``.env`` file, you need to call the ``$dotenv->overload();`` method - see https://github.com/vlucas/phpdotenv#immutability

**Comment by rquadling** [comment]
If you go to your command prompt and type ``set``, you should see the pre-existing (or at least recently configured) environment variables. If you see ``username``, then this is what will normally be provided to the ``$dotenv->load()`` method.

**Comment by ssi-anik** [comment]
Thanks for your information.

**Comment by rquadling** [comment]
You're welcome.
