### ISSUE TITLE
PSR-4 Compliance?

### ISSUE THREAD

**Issue by pmjones** [vlucas/phpdotenv#14]
One nice-to-have would be a PSR-4 namespace so that it does not conflict with any hypothetical Dotenv class from some other project.  The "fix" (such as it is) would be to put the Dotenv class in a namespace, such as `vlucas\` or something like that.

**Comment by vlucas** [comment]
This is now in v2.0.0: https://github.com/vlucas/phpdotenv/releases/tag/v2.0.0
