### ISSUE TITLE
Can you provide release note?

### ISSUE THREAD

**Issue by lichunqiang** [vlucas/phpdotenv#142]
Today I find my env:
```
 - Removing vlucas/phpdotenv (v2.0.1)
 - Installing vlucas/phpdotenv (v2.1.0)
```

But i don't know if there any bc changes...

**Comment by GrahamCampbell** [comment]
> But i don't know if there any bc changes...

We follow semver, so no breaking changes.

**Comment by GrahamCampbell** [comment]
Major releases are breaking, minor are new feature, or just more significant changes, and patch are bug fixes or cleanup type things.
