### ISSUE TITLE
Laravel 5.2 having trouble with Dotenv

### ISSUE THREAD

**Issue by orzilca** [vlucas/phpdotenv#146]
After upgrading Laravel 5.1 to 5.2 I'm getting the following error:

```
hp artisan serve --port=8888
PHP Fatal error:  Using $this when not in object context in /Applications/XAMPP/xamppfiles/htdocs/.../vendor/vlucas/phpdotenv/src/Dotenv.php on line 40

Fatal error: Using $this when not in object context in /Applications/XAMPP/xamppfiles/htdocs/.../vendor/vlucas/phpdotenv/src/Dotenv.php on line 40
```

Tried removing `vendor` directory and re-run composer install.
Keeps getting the same errors..

* Using OSX, php5.6.15 and latest version of composer

**Comment by GrahamCampbell** [comment]
Looks like you have some code trying to call load statically.

**Comment by GrahamCampbell** [comment]
I see what's going on here. You need to delete your compiled.php file from the bootstrap/cache folder in your laravel application.

**Comment by orzilca** [comment]
Hi @GrahamCampbell,

Few months ago I've set multiple environments following this guide:
http://developers.ph/laravel-framework/laravel-5/how-to-setup-multiple-environment-for-laravel-5-developers-way/

It seems to be using static calls, as you noticed.
I've edited my code, removed the static calls - everything is working now..

tnx
