### ISSUE TITLE
Restrictions on nested variables

### ISSUE THREAD

**Issue by bcarroll22** [vlucas/phpdotenv#151]
Hi, I was just wondering if there was a reason why nested variables are restricted to only having alphanum plus underscores? This has caused issues in our dev environment because we can't do things like namespacing properties with dots, or doing array syntax properties, which would be very useful for our team. Is there any reason why this cannot be done with this package?

Also we're required to use v1.1 because we're on Laravel 5.1 LTS, so if we could get the enhancement made on that branch I'd appreciate it. If it's good to go into the package, I'd be willing to make the modification and submit a PR.

For clarification, what I'm looking for is the ability to do nested variables such as:

```
APP[0].URL=whatever
```

and then be able to nest those with:

```
API[0].URL={$APP[0].URL}
```

For the record, that's not really a use case we're looking for, it was just something easy I came up with off the top of my head. Thanks!

**Comment by marcuschaplais** [comment]
You can do this with https://github.com/josegonzalez/php-dotenv -- maybe vlucas/phpdotenv should think about using the env parser by m1:https://github.com/m1/Env like the josegonzalez/php-dotenv package?

**Comment by GrahamCampbell** [comment]
The 1.1 branch is there for bug fixes. New stuff goes into 2.x.
