### ISSUE TITLE
xdebug doesnt look so good: cache env results feature?

### ISSUE THREAD

**Issue by sshilko** [vlucas/phpdotenv#156]
![screen shot 2016-01-29 at 11 51 45](https://cloud.githubusercontent.com/assets/1147808/12673738/c95f8822-c67e-11e5-882c-fd660e78b1bf.png)

Is any caching feature planned? I'm thinking of forking to cache the ENV results to simply php array

**Comment by GrahamCampbell** [comment]
I'd recommend only loading once to populate a config system, then cache the entire result, like laravel does.

**Comment by GrahamCampbell** [comment]
It fixes issues with threading too.

**Comment by sshilko** [comment]
i ended up caching with plain arrays otherwise too slow :(

**Comment by GrahamCampbell** [comment]
yes, that's exactly how laravel does it, usin var_export, then require.
