### ISSUE TITLE
setEnvironmentVariable not populating $_ENV if the variable exists in $_SERVER and vice versa

### ISSUE THREAD

**Issue by sshilko** [vlucas/phpdotenv#158]
under https://github.com/symfony/process 
```
$dotenv = new \Dotenv\Dotenv($path', $file);
$dotenv->load();
```

does not fill $_ENV but only $_SERVER

**Comment by GrahamCampbell** [comment]
?

**Comment by sshilko** [comment]
gimme a minute to get more debug info, but behaviour is weird.
```
PHP 7.0.1-5+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
cli
```

**Comment by sshilko** [comment]
well, the issue is that if
```
immutable=true
```

and the value exists in $_SERVER the code stop there, not checking that variable does not exists in $_ENV for example

see
```
getEnvironmentVariable
```

so guess, its "by design"

**Comment by sshilko** [comment]
the issue is when symfony/process spawns a child with ```proc_open```
```
An array with the environment variables for the command that will be run, or NULL to use the same environment as the current PHP process
```
and passing NULL will pass the $_SERVER variables but not $_ENV ones and that causes phpdotenv not to load the variables in $_ENV.. so i'll just switch to ```overload()`` instead of ```load()```

**Comment by sshilko** [comment]
would be nice if the ```phpdotenv``` actually checks all the $_ENV, $_SERVER and makes sure the value is present in both.. as it claims, and not act so "optimistic" inside  ```setEnvironmentVariable```
