### ISSUE TITLE
Enviroment variables are copied to subrequests if they are on same server

### ISSUE THREAD

**Issue by oliski** [vlucas/phpdotenv#160]
Problem reproduction:
1. Create a project with phpdotenv (I have Laravel project). Let's call it sandbox.
On this project, create .env files with at least one row, for example:
`DB_SECRET=secretkey`
2. Create a second project, on different hostname(however, on same machine/server)
On second project, create a webpage with just following lines:
```
<?php
echo getenv('DB_SECRET');
```

3. In first project, create a page that does request to second project:
```
<?php
/** Your autoload, including phpdotenv */
echo file_get_contents('http://secondproject.local/url.php');

```
4. Open url in browser. 
You can see that project B received enviroment information from project A.

Possible solution: 
Remove putenv() call, use only $_ENV and $_SERVER calls.

I can confirm problem for PHP+Apache connection on Windows 8. 
PHP Version 5.6.16

**Comment by rquadling** [comment]
:+1:

**Comment by oliski** [comment]
Here is the bugreport to php.net
https://bugs.php.net/bug.php?id=71607

Problem is in putenv itself, however, it will not be fixed.
