### ISSUE TITLE
load/overload should return the array variables

### ISSUE THREAD

**Issue by renatomefidf** [vlucas/phpdotenv#161]
When I call the load functions I get a list which is like this:
```
array(2) {
  [0] =>
  string(22) "SYMFONY_ENV=production"
  [1] =>
  string(15) "SYMFONY_DEBUG=0"
}
```
I don't want to parse it again, it would be nice to have the key value as `const => value`, this way I can proceed with my own customization.

What led me to this is because dotenv doesn't convert booleans to proper typing and in the issue you say its not going to be implemented, but I want to do it in my own software right after loading the variables and rewrite them if I need to.

Do you think its a viable solution to change the return type of load/overload or provide a way to read those variables back?

Thanks!

**Comment by GrahamCampbell** [comment]
Duplicate issue.

**Comment by renatomefidf** [comment]
@GrahamCampbell could you link the main issue?
