### ISSUE TITLE
Html snippet

### ISSUE THREAD

**Issue by brunogoossens** [vlucas/phpdotenv#165]
Hey,

What is the best way to get a multiple line snipped assigned to a variable without using quotes (so there is no need to escape quotes)?

Example (.env):

```
TRACKING_SNIPPET=
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-XXXXX-X']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
```

I noticed that putting the whole snippet on 1 line works but I'm looking for a better approach.

**Comment by GrahamCampbell** [comment]
I wouldn't recommend using environment files in this way.

**Comment by brunogoossens** [comment]
Why not? This snippet changes for every environment.

**Comment by tuupola** [comment]
Better just store the `UA-XXXXX-X` in environment.

**Comment by brunogoossens** [comment]
Well it should work for google analytics but also for Piwik that uses an other snippet.
