### ISSUE TITLE
env vars not loading inside iframe

### ISSUE THREAD

**Issue by iadj** [vlucas/phpdotenv#167]
I have a PHP project running on Yii2 (configured to use `https` on localhost, no certiciate). I'm using a `.env` file with the `vlucas/phpdotenv` package to load my config variables.

When I have a page containing an iframe, and the iframe wants to access env vars, all env vars return 0. When I reload the iFrame using Javascript after the page has completely loaded, the env vars are loaded properly into the iframe.

For example:

index.php:

    ...
    
    ...
    <iframe src="file_using_env_vars.php" />

file_using_env_vars.php:
`<?=getenv('SITE_NAME')?>`

The site name is displayed if the php file is loaded directly in the browser, or if it's (re)loaded using Javascript after a few seconds. It never displays properly if the iframe is loaded normally using `src`.

**Comment by rquadling** [comment]
If you load the iframe url directly (i.e. not in an iframe), do you see the same error?
Is .html treated as .php by your server? If not, how can index.html process PHP code?

Most likely, your file_using_env_vars.php isn't loading the phpdotenv to parse your .env file.

**Comment by iadj** [comment]
@rquadling That's an error in the example. I use Yii2, so there's no actual HTML pages. It's all processed by the framework's MVC.

**Comment by rquadling** [comment]
I think you are seeing the putenv() issue that PHP has.

https://github.com/vlucas/phpdotenv/issues/109
https://github.com/vlucas/phpdotenv/issues/76#issuecomment-167806230

**Comment by iadj** [comment]
@rquadling Very interesting. This is indeed probably it. I'll use my framework's global variables to load my configurations instead.
