### ISSUE TITLE
Provide autoloader by default

### ISSUE THREAD

**Issue by tiborsaas** [vlucas/phpdotenv#173]
Just an improvement suggestion. 

Currently usage relies on composer. What if I don't want it? I should require 8 files on top of my index.php which is not really nice. 

Adding an autoloading function would be handy or at least please update the readme.md file how to use donenv without composer.

**Comment by GrahamCampbell** [comment]
I don't see the point? Just use composer's autoloader.

**Comment by GrahamCampbell** [comment]
Even if you don't want to install using composer, just find a PSR-4 autoloader yourself, That's the entire point of PSR-4.

**Comment by tiborsaas** [comment]
@GrahamCampbell Some cases I just don't want to use composer. In this case I have a CMS and I haven't touched a single line of PHP, nor the CMS uses composer. 

PSR-4 is a good point, but that's something I'm requesting here to add it to the docs for newbies who might not know what PSR is.

**Comment by GrahamCampbell** [comment]
I think that's unnecessary. That's something everyone should bother to look up first.

**Comment by tiborsaas** [comment]
That's a funny mindset to assume everybody should know everything before using your lib. Just as you think PSR is a good practice, I think considering other use cases should be best practice too. 

For example the guy who deployed the CMS don't know PHP. Shall I start explaining everything to him or go with a dead simple option? I picked the latter.

**Comment by rquadling** [comment]
@tiborsaas, PSR-4 exists so we don't have to write our own autoloaders. As for having a library that is PSR-4 compliant require supplying it's own autoloader, adding to the bloat of every installation that uses a PSR-4 compliant autoloader, in addition to the maintenance of the nearly completely redundant autoloader ... not worth the effort.

With 1 reference, PSR-4, you've increased your knowledge, the knowledge of your team and everyone is happy. No additional code to write, no additional code to maintain.

The mindset is to increase knowledge and provide stable software, not to support every potential edge case that already has any number of pre-invented wheels ready to roll.

**Comment by tiborsaas** [comment]
Where does the readme say I should use PSR? How is it obvious from it if you don't know what PSR is?

**Comment by rquadling** [comment]
As for the example of your guy, if he doesn't know PHP, why is he even bothering with include a library that does nothing without coding?

And personally, explaining things to him means you now have 2 people capable of doing the work when you get hit by that proverbial bus/lorry/train/truck.

Still no reason to re-invent a perfectly understood, well tested, working solution.

**Comment by rquadling** [comment]
> Where does the readme say I should use PSR? How is it obvious from it if you don't know what PSR is?

In fairness to every single library out there, how many DO mention the need for a PSR-4 loader? Well, probably none of them as they tell you to install using composer, which has a PSR-4 loader.

**Comment by rquadling** [comment]
This is a training issue, not a development/technical issue. Solve it using training.

**Comment by rquadling** [comment]
And autoloading has been around since 13 July 2004. 11 years. Nearly. Not a new thing.

http://php.net/manual/en/language.oop5.autoload.php

**Comment by vlucas** [comment]
@tiborsaas This library supports standard autoloading, which has been in use for over a decade in PHP. This library will not ship with its own autoloader, for reasons stated by others in this thread. Just register the 'Dotenv' namespace to the folder you install this package into, and everything will work as expected, even if you don't use Composer.

**Comment by tiborsaas** [comment]
Thanks for the feedback. If you think the documentation is perfect then just ignore me, sorry for bikeshedding :) I'm a bit bullish on dev UX, which is often terrible, because people just assume that everybody knows everything.
