### ISSUE TITLE
.env file inheritance

### ISSUE THREAD

**Issue by matejvelikonja** [vlucas/phpdotenv#174]
I am wondering if phpdotenv supports `.env` file inheritance. What I mean with that, is that you have one main `.env` file and another one which just overrides values from the first one.

**Example**
```bash
# .env_base
VAR1=1
VAR2=2
VAR3=3
```

```bash
# .env
extend .env_base #or something like that

VAR3=33
VAR=4
```

and the results of this would be:
```bash
VAR1=1
VAR2=2
VAR3=33
VAR=4
```

**Comment by GrahamCampbell** [comment]
Just load them both, and the 2nd one will override the first one.
