### ISSUE TITLE
Error in nginx/HHVM

### ISSUE THREAD

**Issue by sfolador** [vlucas/phpdotenv#178]
Hi, 

the file Loader.php at line 340 shows an error in nginx/HHVM because "apache_getenv" doesn't exist.

The problem is solved with:   

if (function_exists('apache_setenv') && **function_exists('apache_getenv')** && apache_getenv($name)) { ....

**Comment by vlucas** [comment]
Argh! This just had to happen. I don't even know how one function would be defined without the other... *sigh*
