### ISSUE TITLE
Load variables into named constants with define()

### ISSUE THREAD

**Issue by Patabugen** [vlucas/phpdotenv#180]
I'm using dotenv with WordPress where the configuration needs to go into named constants, than than $_ENV.

`define('DB_NAME', "value-from-dotenv');`

I'd like dotenv to be able to load the contents of my .env file as constants (if they're not already set) - (and optionally be able to not touch $_ENV or $_SERVER since they're of no use to me - but that's a slightly different issue).

Rather than iterating over the whole of $_ENV and defining everything, it'd be nice to be able to have dotenv set them for me.

**Comment by Patabugen** [comment]
Why was this closed? (i.e. is it happening, or not happening?)

**Comment by GrahamCampbell** [comment]
This is out of the scope of this. It's trivial for you to write this code in your app.

**Comment by Patabugen** [comment]
​​It seemed to me that it would fit neatly alongside filling in $_ENV and $_SERVER.

 I imagined something like:

```
$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load('define'); // or perhaps with an array should someone want them in more than one place
```

or perhaps even load them wherever we want
```
$myConfig = [];
$dotenv = new Dotenv\Dotenv(__DIR__, '.env', $myConfig);
```

So we have the same functionality but have control over where the variables end up so we can avoid polluting unwanted namespaces. I do feel like the destination of the variables could do with some more flexibility.

**Comment by schmunk42** [comment]
Related project: https://github.com/neam/php-app-config
