### ISSUE TITLE
early error returning when having spaces in .env comment

### ISSUE THREAD

**Issue by hanihh** [vlucas/phpdotenv#182]
I read the specification of defining the .env file and realize that we can define a variable with spaces inside,
However, using laravel framework version 5.2.35, I got an error when having this line in .env  like this 
`TIMEOUT=100000 # increase if import times out.
`
And the exception gone away when I removed the comment.
 or when change it to 
`TIMEOUT=100000 # "increase if import times out."
`
Regarding to this issue, the thrown exception is 
`Class log does not exist ` 
and it's very hard to know the exact error.

**Comment by GrahamCampbell** [comment]
This is a known bug in laravel, sorry.
