### ISSUE TITLE
Question about Usage

### ISSUE THREAD

**Issue by picosam** [vlucas/phpdotenv#184]
Hello, you're saying that
> phpdotenv is made for development environments, and generally should not be used in production

Where exactly should variables be set then in production environments, Apache for instance? Also, if some variables are required, and the .env file is not found in the production environment, won't that raise an error this way?

Thanks in advance, and sorry if the question is stupid!

**Comment by GrahamCampbell** [comment]
> and the .env file is not found in the production environment, won't that raise an error this way?

You need to catch that exception if you're ok with the file not existing.

> and generally should not be used in production

You can use it in production if you use it one-time to build up config files. What we are meaning is, don't use it to read the .env file on every request.

Regarding both these points, check out how Laravel 5.2 does things.
