### ISSUE TITLE
env file no loading

### ISSUE THREAD

**Issue by NetoBraghetto** [vlucas/phpdotenv#185]
Hello, i am using Laravel 5.2 on a Ubuntu 14.04 machine with php7.
I have an .env file in the project, but the env values aren't loading.
It doesn't show any error...
there is any extension that i am missing?

**Comment by GrahamCampbell** [comment]
Laravel 5.2 does not ever load environment variables other than for populating the config file cache. Don't try to read the environment outside of the config file definitions. Laravel does this due to PHP crappy leaking of information between threads.
