### ISSUE TITLE
Cannot support Octal Numbers

### ISSUE THREAD

**Issue by Patabugen** [vlucas/phpdotenv#186]
One of my environments requires me to set the CHMOD values for file/directory writes, but the octal values in dotenv (identifiable because they start with a 0) are coming out as strings.

```
define('FS_CHMOD_DIR', 0775);
define('FS_CHMOD_FILE', 0664);
```

I tried doing this with phpdotenv:

```
FS_CHMOD_DIR=0775
FS_CHMOD_FILE=0664
```

but they come out as strings `0775` and `0664`.

To work-around I have to add:

```
                switch($key) {
                        case 'FS_CHMOD_FILE':
                        case 'FS_CHMOD_DIR':
                                $value = octdec($value);
                                break;
                }
```

to process them.

I've had a look through the docs, code and issues but cannot see how to make it work out of the box.

**Comment by rentalhost** [comment]
I don't know how DotEnv works related to that, but I guess that it should allow octals as you have quoted, except if it is implicitly a string:

```
FS_CHMOD_DIR = 0775 # Should be octdec()'ex
FS_CHMOD_DIR = \775 # Alternative: as allowed on PHP
FS_CHMOD_DIR = "0775" # Should be keeped as string
```

**Comment by davidjeddy** [comment]
@Patabugen At present I do not believe this lib can do what you ask. Casting the value of the string post retrieval is how I have had to implement non string values myself.
