### ISSUE TITLE
How can I get past permission issues?

### ISSUE THREAD

**Issue by tfarina** [vlucas/phpdotenv#187]
Hi,

When I try to instantiate Dotenv, the page does not load. I think it is because of Linux permissions and thus it is not able to read .env file.

How can I diagnose and fix this problem? When I try to load the page it all blank.

**Comment by GrahamCampbell** [comment]
Thanks, but this is not a support forum. Feel free to ask on one though.

**Comment by tfarina** [comment]
@GrahamCampbell thank you very much!

**Comment by tfarina** [comment]
After reading nginx error logs, I figured out that I had to include Loader.php before Dotenv.php, as I'm not using composer.
