### ISSUE TITLE
return from load functionality

### ISSUE THREAD

**Issue by designermonkey** [vlucas/phpdotenv#188]
Just a question more than anything...

Would it not be better to return the parsed array of key -> value pairs from the load function instead of an array of strings? I'm sure there would be a ton more functionality use cases that would handle an array over the strings?

**Comment by GrahamCampbell** [comment]
Yes, perhaps. We're open to PRs. :)

**Comment by GrahamCampbell** [comment]
I've actually made this change in https://github.com/vlucas/phpdotenv/pull/306, so that load returns an associative array mapping the environment variable names from the file to their values.
