### ISSUE TITLE
Bug with regexp in .env

### ISSUE THREAD

**Issue by chekalskiy** [vlucas/phpdotenv#189]
Here is content of `.env` file:

`STRING = "/^https:\/\/(domain1\.com|domain2\.com)/i"`

`var_dump` of `getenv()` output:

`string(43) ""/^https:\/\/(domain1\.com|domain2\.com)/i""`

Problem is in quotes inside string.

**Comment by rquadling** [comment]
Yeah. This never makes any sense to me. If a string is quoted, the quotes are now part of the string. You have to quote to add a space, but then the quotes are part of the string. Quite mad.

https://github.com/vlucas/phpdotenv/issues/133

**Comment by rquadling** [comment]
There's a lot of history to this issue, including breaking other libs due to a lack of following SemVer.

**Comment by GrahamCampbell** [comment]
I don't think this is a bug then. Your string there does include the quotes as part of itself.
