### ISSUE TITLE
Public Display of ENV vars

### ISSUE THREAD

**Issue by yespbs** [vlucas/phpdotenv#193]
using a <?php echo phpinfo() ?> can expose all .env in ENV global including sensitive info

How to protect it?

**Comment by GrahamCampbell** [comment]
Bit of a trick question really. Never let users see phpinfo(). That's the only problem here.

**Comment by yespbs** [comment]
Truly, it's a mistake I just discovered for a windows server, it seems
since the phpinfo was printed inside a controller, the app loads all env,
there should be a way to unload the sensitive info before using phinfo , I
won't repeat it though 😕
