### ISSUE TITLE
class not found error

### ISSUE THREAD

**Issue by sam0hack** [vlucas/phpdotenv#194]
I installed it with composer when i try to load donenv it's giving me class not found error

`$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->overload();`

**Comment by rocketpastsix** [comment]
Is ```$dotenv->overload();``` a typo?

**Comment by rocketpastsix** [comment]
did you ```use dotenv\dotenv```?

**Comment by GrahamCampbell** [comment]
> did you use dotenv\dotenv

Imports are case sensitive (if you filesystem is). You will need the correct case.

**Comment by OKNoah** [comment]
@sam0hack I solved this by doing `require __DIR__ . '/vendor/autoload.php';` before the line you posted.

**Comment by sam0hack** [comment]
@OKNoah  Thanks :+1:
