### ISSUE TITLE
A way to store values in $_ENV but not $_SERVER

### ISSUE THREAD

**Issue by benjaminkohl** [vlucas/phpdotenv#196]
It was brought to our attention that the $_SERVER super global's contents are dumped to the browser console when a particular CMS is in development mode. While we only do this on the dev site, we'd still like to keep our DB credentials out of the browser console.

Is there a way to make dotenv put/get from $_ENV entirely and not make any changes to $_SERVER?

**Comment by stedaniels** [comment]
See https://github.com/vlucas/phpdotenv/pull/200 this would mitigate this potential vulnerability in the CMS.  Hopefully it'll get merged.

**Comment by GrahamCampbell** [comment]
Done in https://github.com/vlucas/phpdotenv/pull/300. See https://github.com/vlucas/phpdotenv#loader-customization for an example.
