### ISSUE TITLE
setEnvironmentVariable can leave unpredictable state when value is set in one location

### ISSUE THREAD

**Issue by Patabugen** [vlucas/phpdotenv#203]
I've spent several hours tracking down an intermittent (~20% of requests) database issue on localhost.
# Summary

phpdotenv is meant to set your config settings from .env into 3 places - but it won't overwrite already-set values. However if it finds a setting in any one of those three places, it doesn't fill in the others (so you can't be sure that your variables will always be available in all three locations)
# Cause

The problem is when phpdotenv checks whether an environment variable is already set it checks if the variable is set anywhere (getenv, $_ENV or $_SERVER) then it stops - potentially leaving the other places phpdotenv would have filled in blank.
# Test

Run this (you may need to fix the loading of dotenv) - it'll create the .env file it needs.

```
<?php
// Make a .env file (in the script just to make testing easier)
file_put_contents( __DIR__.'/.env', 'some_var="goodbye"');
// Put something in the env
putenv('some_var=hello');

// Now pretend we didn't just fake the .env and server config
require_once(__DIR__.'/vendor/autoload.php');
$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();
echo $_ENV['some_var'];
```
# More Details

The problem is with this function/line here:
https://github.com/vlucas/phpdotenv/blob/3cc116adbe4b11be5ec557bf1d24dc5e3a21d18c/src/Loader.php#L334
# Possible Solution

I can't see a clear fix, but some suggestions:
1. Allow the user to define which environment variables it would like you to look at/consider (e.g. I could say $_ENV and phpdotenv would ignore put/setenv and $_SERVER)
2. When checking if a variable is already set, copy it's value to the other places (so dotenv always leaves you with a predictable outcome)
# Workarounds

My .env contains everything and my code doesn't (currently) run anywhere I'd need to override settings in it - so I've replcaed:
`$dotenv->load()` with `$dotenv->overload()` which skips checking whether a variable is already set and always sets them all - solving my issue.

Another workaround would be to figure out which variable store is giving you problems - and using that (e.g. if it's your $_SERVER['DB_HOST'] variable is already set don't use $_ENV['DB_HOST'] because it might not be set).
# My actual issue

The actual issue which caused me to look into this is my WAMP stack which appears to be sharing get/putenv variables between simultaneous processes. So if I load my page 10 times the first would work, but all the other requests would fail because $_ENV['DB_HOST'] is not set because phpdotenv saw it in `getenv` and then did not set the $_ENV (which I use).

**Comment by dagrofaloyalty** [comment]
Why not just read them from wherever and provide an access API, so conf reading is done from this module. Like so: $dotenv->get('DB_HOST');

**Comment by GrahamCampbell** [comment]
Thanks for the report. Please see https://github.com/vlucas/phpdotenv/issues/219.

**Comment by GrahamCampbell** [comment]
I think it's likely the following example will work in a multithreaded environment. This avoids using the adapter that would have called `putenv` and `getenv`, which are not threadsafe.

```php
<?php

use Dotenv\Environment\Adapter\EnvConstAdapter;
use Dotenv\Environment\Adapter\ServerConstAdapter;
use Dotenv\Environment\DotenvFactory;
use Dotenv\Dotenv;

$factory = new DotenvFactory([new EnvConstAdapter(), new ServerConstAdapter()]);

Dotenv::create($path, null, $factory)->load();
```
