### ISSUE TITLE
Load multiple env files

### ISSUE THREAD

**Issue by rudolphp** [vlucas/phpdotenv#205]
Can we pass multiple files to the Constructor to be loaded. Example

$dotenv = new Dotenv\Dotenv(__DIR__ . '/../', ['.file1.env', '.file2.env']);

**Comment by GrahamCampbell** [comment]
No, that's not supported, sorry.

**Comment by GrahamCampbell** [comment]
@rudolphp I'm considering adding this feature to phpdotenv. Please could I have your feedback on #394. I've tried to implement it as to avoid a breaking change, where by default, we won't load all files, only the first file we can find and read.

**Comment by GrahamCampbell** [comment]
This code is currently available as:

```
    "require": {
        "vlucas/phpdotenv": "^4.1@dev"
    },
```

**Comment by GrahamCampbell** [comment]
I'm going to give some more time for feedback before I release 4.1.0.
