### ISSUE TITLE
Possible Issue with readme.md

### ISSUE THREAD

**Issue by govindrai** [vlucas/phpdotenv#206]
Author writes 

> Command Line Scripts

> If you need to use environment variables that you have set in your .env file in a command line script that doesn't use the Dotenv library, you can source it into your local shell session:
> 
> `source .env`

However, I am under the impression that doing so will not create environment variables as the file is missing the `export` command in front of all variables that would exist in that .env file. In fact, I've tested this before opening this ticket. But hopefully I'm wrong. :)

Thank you!

**Comment by danhunsaker** [comment]
It isn't properly documented, but phpdotenv does support having `export ` before any and all variables (it explicitly checks for it and handles it appropriately).  So go ahead and add the `export `s.

**Comment by kAlvaro** [comment]
I'm not a Unix expert but `export` only seems to be necessary with actual scripts (`e.g.` executable files with `#!/bin/sh`). The `source .env` command exports variables in my copy of Ubuntu running bash.

**Comment by GrahamCampbell** [comment]
I think so. :)
