### ISSUE TITLE
Not for production

### ISSUE THREAD

**Issue by theofidry** [vlucas/phpdotenv#207]
>phpdotenv is made for development environments, and generally should not be used in production. In production

Ok I guess there is reasons for that, however this should not be a regular text lost in the middle of the readme, but rather a big fat warning at the beginning. Especially considering that in the introduction we mention good use cases which are perfectly valid for production.

And I also think any Laravel user would get very confused by that.

**Comment by GrahamCampbell** [comment]
Laravel doesn't "use the library in production" as such. It uses it to one-time populate a config cache, and then the library is not used when actually serving requests.

**Comment by theofidry** [comment]
@GrahamCampbell why closing it? Laravel was one illustration, the actual problem is still there.

**Comment by GrahamCampbell** [comment]
Hmm, I'd really say the problem lies with PHP rather than this library, so anyone consuming it should already be aware of PHP's issues.

**Comment by theofidry** [comment]
Tbh I'm not sure why it's not suitable for production as it's not stated in that paragraph. I've seen #196 and #163 which relates to potential security issue and a mention in #163 that it may cause unnecessary disk access.

But in any case, I would love to see a clearer warning/explanation :)

**Comment by stephan-v** [comment]
Just out of personal curiosity but what happens if the Laravel config cache gets dumped somewhere? With the populated data? Would this mean all the data would be in the open?

**Comment by GrahamCampbell** [comment]
Laravel doesn't use dotenv in production, the idea is it caches the config file, loading the env in a fresh php process from the command line, then never loads the env file in production requests.

**Comment by theofidry** [comment]
@GrahamCampbell I'm not sure why you're keen to close this issue: it's not Laravel related but rather about *why* this library is not production (except the potential disk access, but some may not care) and about the message itself, which is completely hidden in the readme.

**Comment by GrahamCampbell** [comment]
I'd argue this is just a design floor in PHP. If someone wants to add a PR to the readme to point this out, I guess I'd be fine with that. I'd recommend only using this library, or any other related libraries, in conjunction with a system, similar to the one Laravel provides.

**Comment by vlucas** [comment]
@theofidry In production, ideally all these variables will already be loaded in the environment though things like Apache's `SetEnv` directive, etc. PHP's execution model (shared nothing) does not work well with having to read the contents of a file for every single request, thus the reason I say this library was not designed for production, but rather for development, to help you _emulate_ the production environment variables being set.

**Comment by theofidry** [comment]
Thanks for the explanation @vlucas :)

**Comment by GrahamCampbell** [comment]
Though, there's no need to do things with the environment features of apache, if you follow a configuration model, such as laravel's, which is only ever access the environment variables from inside config files, which are then evaluated, and stored for later.

**Comment by GrahamCampbell** [comment]
I think it's likely the following example will work in a multithreaded environment. This avoids using the adapter that would have called `putenv` and `getenv`, which are not threadsafe.

```php
<?php

use Dotenv\Environment\Adapter\EnvConstAdapter;
use Dotenv\Environment\Adapter\ServerConstAdapter;
use Dotenv\Environment\DotenvFactory;
use Dotenv\Dotenv;

$factory = new DotenvFactory([new EnvConstAdapter(), new ServerConstAdapter()]);

Dotenv::create($path, null, $factory)->load();
```
