### ISSUE TITLE
Array argument to DotEnv constructor

### ISSUE THREAD

**Issue by sminnee** [vlucas/phpdotenv#213]
It would be helpful to be able to specify an array of paths in the DotEnv constructor:

```php
$env = new DotEnv([__DIR__, dirname(__DIR__)]);
```

The semantics would be that the first path that contains a .env file would be used.

The use-case is that sometimes it's better to put .env outside of your project root, e.g. if your project code is deployed separately from .env or if you're using a common .env for multiple projects.

Would you accept a PR to this effect?

**Comment by GrahamCampbell** [comment]
Thanks for the suggestion. We're open to PRs to `master`, which will become v3.0. :)

**Comment by GrahamCampbell** [comment]
I've decided to implement this myself at https://github.com/vlucas/phpdotenv/pull/307.

**Comment by GrahamCampbell** [comment]
@sminnee Please let me know if the implementation in V3 does what you need.

**Comment by sminnee** [comment]
Thanks Graham I’ll revisit where we got to and see how this can reduce the amount of code duplication. I see you’ve commented on the relevant PRs on the SilverStripe project. :-)
