### ISSUE TITLE
Using .env in dev (Windows)

### ISSUE THREAD

**Issue by CedNet** [vlucas/phpdotenv#216]
Hi! I have plenty of Laravel projects and the .env files are acting weirdly.

One project may sometimes (mostly) pick up the value from another project on the system if it has the same variable name (standard .env file from a Laravel project). This can lead to some very misleading situations such as QUEUE_DRIVER being file or redis and so on. 

For Laravel you may use php artisan config:cache then the configs sticks as it actually reads the local file and caches it for Laravel.

But during dev I rather not use Laravels cached version as the .env variables might change a fair bit during development. 

What do do here?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. I don't quite understand the problem though?

Are you reading env variables outside of the config files? If so, please don't. Laravel doesn't bother loading the .env file at all if config is cached. This is due to a PHP bug inherently affecting environment variables, making them basically unusable if you have more than one website per process.

**Comment by CedNet** [comment]
I use WAMPServer and it doesn't support having different PHP processes per site / host..., if that's the cause for variables being stored and values the same across many sites.

I fetch the variables via Laravels config('app.url') and that config/app.php URL value is itself fetched with env('APP_URL') which comes from .env. So nothing special with that.

I don't believe XAMP or MAMP supports multiple PHP versions running at the same time either. There really should be such a server made for PC and Mac.

**Comment by GrahamCampbell** [comment]
> I don't believe XAMP or MAMP supports multiple PHP versions running at the same time either. There really should be such a server made for PC and Mac.

Yeh, it's not something I would recommend, but environment variables will leak into other threads unfortunately, so php's system is just broken to the core. I'd recommend always using a system like laravel's config caching, never read environment variables outside of those files.

**Comment by kAlvaro** [comment]
I suggest you replace `env('APP_URL')` with `$_SERVER['APP_URL']`. When you run PHP as Apache module on Windows, environment variables are shared by different processes in the same thread.

**Comment by GrahamCampbell** [comment]
> I suggest you replace env('APP_URL') with $_SERVER['APP_URL'].

I'd definitely **not** recommend doing that, especially since it won't even work, when config caching is turned on, and it's not recommended to deploy to production without config caching.

**Comment by GrahamCampbell** [comment]
It also won't work correctly with test suites.

**Comment by GrahamCampbell** [comment]
TBH, it sounds like this whole issue is mitigated by using config caching.
