### ISSUE TITLE
Failure on loading long quoted values

### ISSUE THREAD

**Issue by igor-krein** [vlucas/phpdotenv#218]
Tried to set the environment variable like
PRODUCT_KEY="......"
with the comparatively long value (200+ characters). The phpdotenv Loader failed to load it (which resulted in "connection reset" error in Firefox). It looks like the problem arises when calling the preg_replace function from Loader::sanitiseVariableValue.

I am using WAMP (on Windows 7), PHP 5.5.12. Didn't check it on other OS/PHP versions. Have played a little with pcre settings in php.ini, but to no success. It is possible that the value critical length limit depends on environment; in my case, it is equal to 195 characters.

**Comment by kAlvaro** [comment]
I've just retrieved successfully a 17825 char string.

Have you configured your PHP development box to display error messages?

**Comment by igor-krein** [comment]
It looks like PHP is just crashing silently. I see only reports in logs of Apache and Windows Event Viewer. File php5ts.dll is the faulty one. I don't know much of regex functions, but now I suspect that the bug is in the PHP itself rather than in phpdotenv. If you think the same, feel free to close the issue.

**Comment by igor-krein** [comment]
I've located the problem, and it is not related to DotEnv, so I am closing the issue. The problem lies in Apache for Windows, it has a really tiny stack by default, so even not too deep recursion leads to its crash (and, I believe, regex function use recursion a lot). I've increased the stack, and now everything works smoothly. Thanks for the useful tool (and sorry for the false alarm)!

**Comment by rquadling** [comment]
MS-DOS, et al, used to also have a very limited mechanism for the environment.

I don't know how much has changed, but the environment was stored in a page (or pages) of ram before the application was loaded from the shell.

As a consequence, an application could manipulate the environment to a certain degree - upto the page boundary. After that ... BOOM!

I'm hoping that this isn't still the case on a modern Windows.
