### ISSUE TITLE
Add allowable values to Validator::allowedValues() failure message

### ISSUE THREAD

**Issue by j4m3s** [vlucas/phpdotenv#221]
It would be useful if the failure message generated by `Validator::allowedValues()` included the list of valid options.  Happy to supply a PR if you agree.

**Comment by GrahamCampbell** [comment]
Thanks for the suggestion. We're open to PRs to `master`, which will become v3.0. :)

**Comment by GrahamCampbell** [comment]
I've gone ahead and implemented this: https://github.com/vlucas/phpdotenv/pull/309.

**Comment by GrahamCampbell** [comment]
@j4m3s Please let me know if the implementation in V3 does what you need.
