### ISSUE TITLE
ini_set is not allowing composer update

### ISSUE THREAD

**Issue by manzwebdesigns** [vlucas/phpdotenv#225]
Hi,

I am trying to make a site live on a Ubuntu 16.04 (Xenial) install using PHP 7.1 and when I run composer update it errors out during post install/update complaining about ini_set not being allowed because of the security issues.  Here is the error message from the screen output:

```
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan clear-compiled

                                                    
  [ErrorException]                                  
  ini_set() has been disabled for security reasons  
                                                    

Script php artisan clear-compiled handling the post-update-cmd event returned with an error

                      
  [RuntimeException]  
  Error Output:       
                    

```
and here is from the error_log:

```
[19-Feb-2017 19:58:41 UTC] PHP Warning:  ini_set() has been disabled for security reasons in /home/accfs/public_html/vendor/vlucas/phpdotenv/src/Loader.php on line 134
[19-Feb-2017 19:58:41 UTC] PHP Warning:  ini_set() has been disabled for security reasons in /home/accfs/public_html/vendor/vlucas/phpdotenv/src/Loader.php on line 136
```

and here are the lines it is complaining about:

```
cat vendor/vlucas/phpdotenv/src/Loader.php | grep ini_set
        ini_set('auto_detect_line_endings', '1');
        ini_set('auto_detect_line_endings', $autodetect);
```

EDIT: I changed the PHP version back to 7.0 and it is now working, so it is not killing me... yet. :+1: 

Thanks,
Bud

**Comment by tomzx** [comment]
Your PHP environment is simply configured to disallow the use of ini_set. You can either change that (edit the [`disable_functions`](http://php.net/manual/en/ini.core.php#ini.disable-functions) so it doesn't contain ini_set, or phpdotenv should replace those lines with something like

```
$lines = str_replace("\r", '', $lines);
$lines = file($filePath, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
```

so that `ini_get` and `ini_set` are not necessary.

**Comment by manzwebdesigns** [comment]
Thanks, @tomzx, that looks good.
