### ISSUE TITLE
Loader::sanitiseVariableValue() fails with quoted value containing backslash

### ISSUE THREAD

**Issue by wollanup** [vlucas/phpdotenv#230]
Version used is `"vlucas/phpdotenv": "^2.4"`

I have this line in `.env` file :
`PATH="C:\myPath"`
`$value` parameter in `Loader::sanitiseVariableValue()` is`string '"C:\myPath"' (length=11)`

Returned `$value` is still the same instead of expected `string 'C:\myPath' (length=9)`

This only happens if string contains backslash (i.e. Windows path), strings with slashes are well handled.

If I escape backslashes (`PATH="C:\\myPath"`) returned `$value` is expected `string 'C:\myPath' (length=9)`

**Comment by jeff1985** [comment]
Same problem here on Win7 running php 5.6.24
Escaping the backslashes solves the problem.

**Comment by oleg-andreyev** [comment]
Fixed by v2.6

**Comment by GrahamCampbell** [comment]
Not so much fixed, it just allows it in undefined circumstances in previous versions. It's banned again in 3.x, but now with proper error messages.

**Comment by oleg-andreyev** [comment]
2.6.1 fixed my issues with backslash
