### ISSUE TITLE
Add Boolean Support

### ISSUE THREAD

**Issue by s-belichenko-sold** [vlucas/phpdotenv#231]
Add processing of boolean variables. For example, I can write in .env:
`APP_DEBUG=false`
but this code return `true` in any case:
`getenv('APP_DEBUG')`
In the end, I have to write something like:
`getenv('APP_DEBUG')=="true"`

**Comment by jpuck** [comment]
related: https://github.com/vlucas/phpdotenv/pull/197

**Comment by GrahamCampbell** [comment]
This is something you can do by making your own env function, like laravel has done. Introducing this here just breaks the ability to have the string `false`.

**Comment by s-belichenko-sold** [comment]
> Introducing this here just breaks the ability to have the string false.
This is an unconvincing argument, in my opinion.

**Comment by fabswt** [comment]
Wouldn't it make sense to add an option for it?

**Comment by GrahamCampbell** [comment]
`putenv` only is allowed to return either a string or false on failure.

**Comment by GrahamCampbell** [comment]
Environment variables **are** strings.

**Comment by s-belichenko** [comment]
> Environment variables **are** strings.

You are [right](https://www.php.net/manual/en/function.getenv.php):

> getenv ( string $varname [, bool $local_only = FALSE ] ) : **string**

Message to all readers. This code will help make working with Boolean variables more enjoyable:

`$dotenv->required('FOO')->isBoolean();`

@GrahamCampbell It might be great to get a new method from the main library class that replaces the standard function get_env().

**Comment by cja-github** [comment]
Solution:

filter_var($_ENV['var'], FILTER_VALIDATE_BOOLEAN)

From https://stackoverflow.com/a/10645030

**Comment by Argee88** [comment]
Wouldn't it be a possibility to treat boolean values the way it is done [here](https://github.com/josegonzalez/php-dotenv#usage)?
```
# unquoted values containing [null, true, false] are turned into
# their PHP equivalents
PHP_NULL=null
PHP_TRUE=true
PHP_FALSE=false

# when quoted, they are simply string values
STRING_NULL="null"
STRING_TRUE="true"
STRING_FALSE="false"
```
This seems reasonable and intuitive to me...

**Comment by vouza** [comment]
The downside of this solution is that you have to know the type of value before you access it. It will either return FALSE or TRUE - also if it is a number or a string or even null. 

Instead I have written a function, that does return a safe value. 
`function __base_kit_env($val) {
  if (function_exists('getenv')) {
    return filter_var($_ENV[$val], FILTER_VALIDATE_BOOLEAN) ? TRUE : (stripos($_ENV[$val], 'false') === 0 ? FALSE : ((int)$_ENV[$val] > 0 ? (int)$_ENV[$val] : $_ENV[$val]));
  }
  return null;
}
`
