### ISSUE TITLE
Q: Not set Value

### ISSUE THREAD

**Issue by Niko9911** [vlucas/phpdotenv#232]
Main Problem, When ENV_VARIABLE is empty it needs to return null to variable. Is this possible?

Problem: Setting empty value example: `ENV_VARIABLE=`
Result:  `Dotenv values containing spaces must be surrounded by quotes.`

Bypass Attempt 1: Setting value to `ENV_VARIABLE=""`
Result: `$var = getenv('ENV_VARIABLE');` and variable is empty, not null.

Bypass Attempt 2: Setting value to `ENV_VARIABLE=null`
Result: `$var = getenv('ENV_VARIABLE');` and variable type is `string` with value `null`.

**Comment by jpuck** [comment]
How about don't have the variable at all in your `.env`

Or you could unset it in php with `putenv('ENV_VARIABLE');`

**Comment by Niko9911** [comment]
Thanks for quick reply! 

I have following array. It's good idea to keep those values in `.env` file. Of course I can do if statements for 6 values in array, but it's just waste. Any ideas?

         $yhteys = array(
                    'driver'    => getenv('DB_DR'),
                    'user'      => getenv('DB_UN'),
                    'password'  => getenv('DB_PW'),
                    'host'      => getenv('DB_IP'),
                    'port'      => getenv('DB_PT'),
                    'dbname'    => getenv('DB_DB'),
                    'unix_socket'=> getenv('DB_SC'),
                    'charset'   => $config['db.charset'],
                    'ssl_key'   => getenv('DB_MY_SSL_KEY'),
                    'ssl_cert'  => getenv('DB_MY_SSL_CRT'),
                    'ssl_ca'    => getenv('DB_MY_SSL_CA'),
                    'ssl_capath'=> getenv('DB_MY_SSL_CAPATH'),
                    'ssl_cipher'=> getenv('DB_MY_SSL_CIPHER'),
                );

**Comment by jpuck** [comment]
If you must keep them in `.env` for documentation, then you could comment them out with a `#` for later use if needed.

    # ENV_VARIABLE=default

**Comment by Niko9911** [comment]
Oh... Thanks, good point. Didn't even know that was possible, maybe it's time to get some sleep. Seems like my common sense is already sleeping.

**Comment by Niko9911** [comment]
Oh... Thanks, good point. Didn't even know that was possible, maybe it's time to get some sleep. Seems like my common sense is already sleeping.
