### ISSUE TITLE
trim the last spaces in the values of prisoners in quotes

### ISSUE THREAD

**Issue by ikee87** [vlucas/phpdotenv#234]
Hi!
in file .env i have line
```
XI_SERVICE_PASSWORD="MY PASSWORD WHIT LAST SPACE "
```
In result i have string whit out last space... =( fix this.

https://github.com/vlucas/phpdotenv/blob/master/src/Loader.php#L257

**Comment by rgehan** [comment]
Is this really bad behavior ?
Test cases in [tests/Dotenv/DotenvTest.php]() seem to imply it is like this on purpose

**Comment by Korbeil** [comment]
Since it's explicit value between double quotes, it should not be trimed.

**Comment by GrahamCampbell** [comment]
Tripping will be stopped in v3.0, implemented in https://github.com/vlucas/phpdotenv/pull/273. :)
