### ISSUE TITLE
Not working when putenv function is disabled in php.ini

### ISSUE THREAD

**Issue by vysokyj** [vlucas/phpdotenv#235]
When putenv function is disbled in php.ini than Dotenv=>load() do ABSOLUTLY NOTHING: no warning, no exception, no functionality - nothing returned from env and getenv functions.
I have tried several hosting servers but the putenv function is disabled everywhere!

**Comment by GrahamCampbell** [comment]
> Dotenv=>load() do ABSOLUTLY NOTHING

Does it? The global variables `$_ENV` or `$_SERVER` should still be populated. It was decided that it was not desirable to crash if we couldn't call `putenv`, in https://github.com/vlucas/phpdotenv/commit/58633a061610ffd731d7fbbc8f7f009d14b2e4cf after an issue was raised.
