### ISSUE TITLE
[PROPOSAL] Allow INI format in .env.ini

### ISSUE THREAD

**Issue by ZiperRom1** [vlucas/phpdotenv#239]
Hi is it possible to handle `INI` file format for this extension ?

I've looked a bit the source code, the method `load` from `Loader.php` could check the file extension like `.env.ini` and parsing the INI file if INI file extension is provided.

There is a simple PHP built in function [parse_ini_file](http://php.net/manual/en/function.parse-ini-file.php) which get all INI variables into an array.

The main advantages of INI file are IDE syntax highlighting, preserve variable type, nesting variables to array.

Would it requires too much work to handle it ?

**Comment by GrahamCampbell** [comment]
Not possible, and I don't plan to add support for it. Thanks though.
