### ISSUE TITLE
Fatal error: Uncaught exception 'Dotenv\Exception\InvalidPathException' with message 'Unable to read the environment file 

### ISSUE THREAD

**Issue by claeusdev** [vlucas/phpdotenv#258]
followed the Docs but i keep getting this error

**Comment by tomzx** [comment]
File is either missing from the specified path or you have permission issues which prevents it from being read.

**Comment by KipchirchirIan** [comment]
See this [https://github.com/vlucas/phpdotenv/issues/345#issuecomment-615956432](url) for more explanation.

**Comment by KipchirchirIan** [comment]
See this [Comment](https://github.com/vlucas/phpdotenv/issues/345#issuecomment-615956432) for more explanation.
