### ISSUE TITLE
Consider a new release

### ISSUE THREAD

**Issue by dereckson** [vlucas/phpdotenv#265]
There is interesting things committed since 2.4.0, like Dotenv\Dotenv::safeLoad() to allow to use an .env file or class environment variables.

Could be interesting to have a new release,  to be able to require a version with the safeLoad method present, instead to use `dev-master`.

**Comment by GrahamCampbell** [comment]
No need to use dev-master. You can still use `2.5.*` or `^2.5` so long as you allow composer to resolve non-stable releases, since composer knows the master branch represents the development state of 2.5.x.

That said, I am planning to get a release out today. :)
