### ISSUE TITLE
sourcing .env file in command line

### ISSUE THREAD

**Issue by christos1984** [vlucas/phpdotenv#267]
Hi all,
Do I understand something wrong regarding usage of this lib in command line?

README mentions that it is enough to source the .env file defined, but sourcing doesn't export the file into env vars but into shell vars (which doesn't work for us).

If I haven't terribly misunderstood something, can you point out what's the error on my though above?

**Comment by vlucas** [comment]
Do you have `export` before your variables? i.e.

`export FOO=bar`

**Comment by christos1984** [comment]
Ah, it works. 
For some reason, after I sourced it the first time with the `export` in .env files it wasn't working, but it might have been some other error muted by the error_reporting level in my other laptop.

In the machine I'm testing now, everything works OK so, consider it as my misunderstanding and thanks for clearing it out ; )
