### ISSUE TITLE
[2.4.0] Fatal error: Uncaught Error: Call to undefined method Dotenv\Validator::isBoolean() 

### ISSUE THREAD

**Issue by WizoneDE** [vlucas/phpdotenv#269]
Version 2.4.0 will create an exception by using the function $dotenv->required('FOO')->isBoolean();

Fatal error: Uncaught Error: Call to undefined method Dotenv\Validator::isBoolean()

**Comment by vimist** [comment]
It looks like the `Validator::isBoolean()` method was added after the 2.4.0 release (literally the first commit after the 2.4.0 release), so it's not yet been included in the composor package.

This functionality was added in b755acf (Oct 1, 2016), whereas the 2.4.0 release (3cc116a) was made Sep 1, 2016. I guess a minor version bump is required to include this.

@vlucas Are there any plans for a 2.5.0 release any time soon? #265

**Comment by GrahamCampbell** [comment]
Yes, I can get a release out today. I'm just going to re-familiarize myself with the state of the 2.4 and master branches, and review the pending PRs.
