### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by mhf-ir** [vlucas/phpdotenv#274]
Many request for fpm load IO ... any cache mechanism ?

**Comment by tomzx** [comment]
Not that I'm aware. However I'm surprised your OS doesn't already handle caching of this file if it gets hit so often.

**Comment by mhf-ir** [comment]
OS layaer is not depend of processing env file and etc.. php variables better to be export via `var_export` into script then via opcache we have performance ... unless any read or write in php script will be load io ...

**Comment by tomzx** [comment]
If you don't mind generating a php file when you put your code in production (as part of your deployment pipeline for example), you could write a script that will create a php file by reading the .env file and creating an array out of the resulting variables. Then you can call `Loader::setEnvironmentVariable` to restore the variables.

**Comment by Korbeil** [comment]
We can imagine using something like: https://github.com/php-cache/array-adapter as an internal caching solution when loading variables ?

There is also: https://github.com/php-cache/filesystem-adapter if you prefer files 👍

**Comment by GrahamCampbell** [comment]
The recommended usage of this library would be to one-time load the env file, and use it to populate config, such as in Laravel, and so runtime performance of this library is not critical. That said, I think the performance is pretty quick, such that I don't see how any sort of cache would improve things?
