### ISSUE TITLE
openssl public keys not parsed anymore

### ISSUE THREAD

**Issue by franksl** [vlucas/phpdotenv#278]
Hi,
I need to store an openssl public key in a .env file.
Before 2.5.0 I had no problems but with 2.5.0 the certificate does not get parsed (empty string).
I tracked the problem and the variable is set to empty string in the sanitiseVariableValue() method of Loader class.
It looks like the change is related to this commit: https://github.com/vlucas/phpdotenv/commit/f84952fe8ff11cc6b249b29a8460d03f050a59f3
The value is set as a single line string with "\n" characters inside, for example:
```
TEST_KEY="-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkq [DELETED] IDAQAB\n-----END PUBLIC KEY-----"
```
Thanks,
Frank

**Comment by Korbeil** [comment]
Could you provide a random test key ? To reproduce and check if still failling after last modification

**Comment by franksl** [comment]
Here's a shorted example of a public key:
```
TEST_KEY="-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt0tvPbpE9txRHNcDj2yW\nvQe6sUUhkqe6wShGQIEi6w8NWGPsxf3hYHdi2akR/gxubU4Uhz808wnY\nIwIDAQAB\n-----END PUBLIC KEY-----"

```

**Comment by Korbeil** [comment]
After some tests, this is related to https://github.com/vlucas/phpdotenv/blob/master/src/Loader.php#L234-L248

Which was changed by https://github.com/vlucas/phpdotenv/commit/f84952fe8ff11cc6b249b29a8460d03f050a59f3

After removing that `*` added, it's working fine.
@danielstokes could you look about a work-around to fix this ?

**Comment by danielstokes** [comment]
Its preg_replace ... my change causes php < 7 to trigger PREG_BACKTRACK_LIMIT_ERROR 
pcre.backtrack_limit can be configured, but I'll look into a fix tomorrow.

**Comment by danielstokes** [comment]
see https://github.com/vlucas/phpdotenv/issues/279 for more details regarding your issue

**Comment by ocram** [comment]
Couldn’t you just use your original public key format from the question (wrapped in double quotes, single line) and escape all occurrences of `\n` as `\\n`? That should work, right?

**Comment by GrahamCampbell** [comment]
First class support for multiline strings will be landing in https://github.com/vlucas/phpdotenv/pull/271.

**Comment by GrahamCampbell** [comment]
> and escape all occurrences of \n as \\n? That should work, right?

Yes. You will need to escape backlashes. As of V3.3, the error message when this is forgotten is more friendly.
