### ISSUE TITLE
is this compatible with PHP 7?

### ISSUE THREAD

**Issue by FLasH3r** [vlucas/phpdotenv#281]
According to php [documentation](http://php.net/list), `list` command returns the array in reverse order in PHP7.

> Warning
> In PHP 5, list() assigns the values starting with the right-most parameter. In PHP 7, list() starts with the left-most parameter.

```
list($name, $value) = $this->normaliseEnvironmentVariable($name, $value);
```

This is not the only place `list` is used, it's just one example of many.

**Comment by Odder** [comment]
The issue you are concerned about is only relevant if you are unpacking into an array.

`list($name, $value) = $someArray` resolves to:

PHP5:  `$value = array_pop($someArray); $name = array_pop($someArray);`
PHP7: `$name = array_shift($someArray); $value = array_shift($someArray);`

As you can see above this results in the same unpacking in both versions, however, if you unpack to an array instead the issue becomes clear:

PHP5:  `$array[] = array_pop($someArray); $array[] = array_pop($someArray);`
PHP7: `$array[] = array_shift($someArray); $array[] = array_shift($someArray);`

Unless I am blind, variable unpacking with the list method into arrays have not been used in this codebase, thus if this doesn't work in PHP7, this is not the cause.

**Comment by GrahamCampbell** [comment]
Yes, this library works with PHP 7. Please take a look at the test suite to convince yourself this is true.
