### ISSUE TITLE
Failing to read UTF-16 encoded .env file

### ISSUE THREAD

**Issue by loics2** [vlucas/phpdotenv#282]
Hi

I'm working with Powershell on Windows, and when I write my `.env` file with a script, `phpdotenv` fails to read the file correctly. This is due to the fact that Powershell internally uses .Net UTF-16 strings by default, not ASCII.

### How to reproduce

In Powershell:

``` powershell
echo "TEST=1234" > .env
file .env
# .env: Little-endian UTF-16 Unicode text, with CR line terminators
```
In Laravel Tinker:
```php
>>> $dotenv = new Dotenv\Dotenv(__DIR__); 
=> Dotenv\Dotenv {#2364}                  
>>> $dotenv->load();                      
=> [                                      
        b"ÿþT\0E\0S\0T\0=\01\02\03\04\0",    
        """                                  
           \0\n                               
           \0                                 
        """,                               
 ]                                      
>>> getenv('TEST')                        
=> false                                  
```
### Expected behavior

Either the variable is set correctly:
```php
>>> getenv('TEST')                        
=> 1234
```
or an exception is thrown if the encoding is not supported.

### Versions

 - Windows 10 (1803)
 - PHP 7.2.2
 - vlucas/phpdotenv v2.4.0

**Comment by GrahamCampbell** [comment]
This is a no-fix I'm afraid, because the encoding was supported, and that was the result. We just had no way of knowing what encoding to choose, so used the wrong one, which resulted in us being able to parse the file, so we had no way of knowing it was wrong.
