### ISSUE TITLE
Cannot overload falsy apache variables

### ISSUE THREAD

**Issue by SpacefulSpecies** [vlucas/phpdotenv#283]
Environment variables set with apache that have a "falsy" value cannot be overloaded.

Related issue #39 (closed) and PR #176 (merged)

### How to reproduce
/.htaccess
```apache
SetEnv APP_DEBUG 0
SetEnv APP_CACHE 1
```

/.env
```bash
APP_DEBUG="1"
APP_CACHE="0"
```

/index.php
```php
<?php

$dotEnv = new \Dotenv\Dotenv(__DIR__);
$dotEnv->overload();

echo $_ENV['APP_DEBUG']; // prints "1" as expected
echo getenv('APP_DEBUG'); // prints "0" but expected "1"

echo $_ENV['APP_CACHE']; // prints "0" as expected
echo getenv('APP_CACHE'); // prints "0" as expected
```

### Proposel to fix
Use a strict false comparison with apache_getenv.

https://github.com/vlucas/phpdotenv/blob/v2.5.1/src/Loader.php#L377
```php
// src/Loader.php:377
apache_getenv($name) !== false
```

**Comment by SpacefulSpecies** [comment]
This was on PHP 7.2.8

**Comment by SpacefulSpecies** [comment]
Created PR #284 with the proposed fix

**Comment by SpacefulSpecies** [comment]
Any chance to tag this merge as the next bugfix version "v2.5.2", so this can be closed? That would be awesome! A big thanks for this handy library for development and testing 👍

**Comment by GrahamCampbell** [comment]
Yeh. :)
