### ISSUE TITLE
Lazy loading variables

### ISSUE THREAD

**Issue by sridesmet** [vlucas/phpdotenv#285]
What about lazy loading the variables?
-> get variable from dotenv via dotenv->get('variable')
-> dotenv checks if the variable exists as an environment variable
-> if not it loads your predefined .env file

This way there will be no I/O in production if you set all env variables.

**Comment by GrahamCampbell** [comment]
Thanks, but I don't think this is needed within the core. This is something that should be done by the caller IMO. Perhaps, like the way Laravel does things.
