### ISSUE TITLE
the preg may out of pcre.backtrack_limit

### ISSUE THREAD

**Issue by fyzzy1943** [vlucas/phpdotenv#290]
e.g.
TEST="aaaaaaaaa vvvvvaaaaa\aaaanaa"

we get an PREG_BACKTRACK_LIMIT_ERROR,

**Comment by fyzzy1943** [comment]
and why we must use double backslash?

**Comment by danielstokes** [comment]
to escape the backslash

**Comment by fyzzy1943** [comment]
> to escape the backslash

thank you, I know it, but I want know why we must use double backslash if use quote. and we can use single backslash when don't use quote. why design by this.

**Comment by GrahamCampbell** [comment]
Thanks for the report, but I couldn't replicate this breaking with an env file containing:

```
TEST="aaaaaaaaa vvvvvaaaaa\aaaanaa"
```

Perhaps you need to increase the value of `pcre.backtrack_limit` on your server.

**Comment by GrahamCampbell** [comment]
@fyzzy1943 I've fixed the error message so it lets you know you need to escape the backslash. It now says "invalid escape sequence" instead of crashing with the preg error.

---

See https://github.com/vlucas/phpdotenv/pull/322.
