### ISSUE TITLE
How to call env varables in a whole app

### ISSUE THREAD

**Issue by marcosdipaolo** [vlucas/phpdotenv#293]
Sorry for the beginner's question, but i never completely understood  how to load the dotenv library.
I have a project where the index page lies in the root directory but some other pages at the `/pages` directory. 
The first question is if I have to call the `(new Dotenv\Dotenv(__DIR__))->load(); ` line in all pages where i'll use env variables. 
And the second question is how to call them from the other pages sitting in the `/pages` directory. 
Last question: isn't there a way to load automatically the environmental  variables in the whole app???

Thanks in advance

**Comment by k1462015** [comment]
You should look into `bootstrapping`, see [here](https://www.binpress.com/php-bootstrapping-crash-course/).

You generally have a php script file that bootstraps your application and handles setting up your environment. All your scripts (whether that be your `index.php` file or `/page` scripts should require this bootstrap file. 

I'm assuming your using composer for packages, so you could have something like this `bootstrap/autoload.php`


```
<?php
// Require composers autoload file
require __DIR__.'/../vendor/autoload.php';

// Setup your env variables
$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();
```

If a script `requires` this bootstrap file, any script that it calls will have the environment variables 
set so you wouldn't need to do `$dotenv->load()` again.

@marcosdipaolo
