### ISSUE TITLE
Inconsistencies for getenv() and $_ENV

### ISSUE THREAD

**Issue by oojacoboo** [vlucas/phpdotenv#295]
**.env file**
```
FOO="test"
```

```php
echo getenv()['FOO']; // Error: key not found
echo getenv('FOO') // test
echo $_ENV['FOO'] // test
```

**Comment by treehousetim** [comment]
getenv is a core php function that returns a string not an array.
http://php.net/getenv

**Comment by oojacoboo** [comment]
@treehousetim incorrect, `getenv` is a core php function that has mixed returned results.  It returns a string if supplied with an argument for an environment variable's key, or it returns an array when supplied with no arguments.

**Comment by treehousetim** [comment]
Whoops - my bad.  What version of PHP are you on?

**Comment by oojacoboo** [comment]
7.2.10

**Comment by treehousetim** [comment]
string getenv ( string $varname [, bool $local_only = FALSE ] )
or
array getenv ( void )


If PHP is running in a SAPI such as Fast CGI, this function will always return the value of an environment variable set by the SAPI, even if putenv() has been used to set a local environment variable of the same name. Use the local_only parameter to return the value of locally-set environment variables.

I'm not sure you can use it in the manner you want. :(

**Comment by oojacoboo** [comment]
@treehousetim yep.  And I updated the code to use `$_ENV` instead.  My point of creating this ticket was to bring this to light and also to encourage updating of the docs, if necessary.  And that's looking like that needs to be done now.

**Comment by GrahamCampbell** [comment]
We'd love a PR to the docs. Thanks. :)
