### ISSUE TITLE
Uncaught Error: Call to undefined function env() in wordpress plugins.

### ISSUE THREAD

**Issue by shangdev** [vlucas/phpdotenv#296]
I wrote a wordpress plugins. And installed phpdotenv with composer.

But it made a mistake. This is error message:
```
<b>Fatal error</b>:  Uncaught Error: Call to undefined function env() in /home/wwwroot/trueniu-php/wp-content/plugins/trueniu-init/trueniu-init.php:85
```

And This is my code:
```
require_once __DIR__ . '/vendor/autoload.php';

$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();

var_dump(env('ACCESS_KEY', ''));
```

And when I modify env to getenv, It work normal.

How to solve it !

Best wishes.

**Comment by treehousetim** [comment]
Use the php function getenv. 

http://php.net/getenv

There are some details about the function that are important so make sure to read the php manual.

**Comment by shangdev** [comment]
@treehousetim 

I know getenv can work normal, But why env not work.

In laravel, I can use env, and set default value.

**Comment by shangdev** [comment]
@Fuxy22 

I git it, Thanks you.
