### ISSUE TITLE
variable with quote length more than 2730, getenv() return null

### ISSUE THREAD

**Issue by kaelli1234** [vlucas/phpdotenv#324]
**v2.4.0**
I have a long json string then I put it in the`.env` file. But when I get it by the `getenv()` or `$_ENV`, it return empty.
So I test then found:
when the variable length more chan 2730,
`Loader.php -> sanitiseVariableValue() -> preg_replace()` return null.
my test .env:
`
test='111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111'
`

**Comment by GrahamCampbell** [comment]
Thanks for the report. I believe this to be fixed as of yesterday's v3.4.0 release.

**Comment by GrahamCampbell** [comment]
@kaelli1234 I've prepared a fix for the 2.x series at https://github.com/vlucas/phpdotenv/pull/325. Please let me know if this fixes your issue.

**Comment by GrahamCampbell** [comment]
@kaelli1234 Hmm, actually I can't replicate this bug in the 2.5.2 release. See the PRs that test this.

**Comment by GrahamCampbell** [comment]
Thanks for the report. I can't replicate this on the most recent release of the 2.x series, or in any of the 3.x releases.

**Comment by GrahamCampbell** [comment]
@kaelli1234 Please confirm that the 2.5.2 release behaves correctly, and also that my implementation at #325 behaves correctly. It will become part of the 2.6.0 release, if we're sure it's correct.

**Comment by GrahamCampbell** [comment]
Examples of the other failing case I had in mind:

* 2.4: https://github.com/vlucas/phpdotenv/pull/331 [FAIL]
* 2.5: https://github.com/vlucas/phpdotenv/pull/332 [FAIL]
