### ISSUE TITLE
[2.6.0] Single quotes parsed literally

### ISSUE THREAD

**Issue by mbrodala** [vlucas/phpdotenv#337]
Since version 2.6.0 single quotes are apparently parsed literally which leads to various issues:

`foo='value with spaces'` is now `'value with spaces'` (was `value with spaces`) and is thus unquoted (as in: not surrounded by double quotes) leading to an error:

> PHP Fatal error:  Uncaught Dotenv\Exception\InvalidFileException: Dotenv values containing spaces must be surrounded by quotes. in /.../vendor/vlucas/phpdotenv/src/Parser.php:7

Due to this, the `$` character cannot be escaped properly anymore:

- `foo='$bar'` is now `'$bar'` (was `$bar`)
- `foo="\$bar"` is `\$bar`
- `foo="$bar"` is `$bar` but this will lead to issues when `.env` is loaded e.g. in Bash which then tries to load a non-existing variable called `bar`

**Comment by GrahamCampbell** [comment]
Please let me know if https://github.com/vlucas/phpdotenv/pull/338 fixes your issue. :)

**Comment by GrahamCampbell** [comment]
I've released v2.6.1 with the parser fixes.

**Comment by mbrodala** [comment]
I've just checked and the latest version restores the previous behavior, thanks a lot!
