### ISSUE TITLE
[3.3] Failed to parse dotenv file due to unexpected whitespace

### ISSUE THREAD

**Issue by kinoute** [vlucas/phpdotenv#341]
Hi,

I understand you made some parsing changes recently. I updated to v3.3.0 and v3.3.1 and on both on them I get this error with this line:

`GOOGLE_DETECTION_URL="https://vision.googleapis.com/v1/images:annotate?key="`

If I remove the `=` at the end before the double quote, it works. But why it failed with it? I use double-quotes. Works perfectly on v3.2.0. Do I miss something here?

Thanks.

**Comment by GrahamCampbell** [comment]
Oh, interesting. Thanks for the report. This looks like a bug. I'll take a look.

**Comment by GrahamCampbell** [comment]
@kinoute Please let me know if https://github.com/vlucas/phpdotenv/pull/342 fixes your issue.

**Comment by kinoute** [comment]
Yep, it fixes the issue. Good job!

**Comment by GrahamCampbell** [comment]
Perfect. I'll release v3.3.2 in the next few minutes.

**Comment by Anskhilji** [comment]
> @kinoute Please let me know if #342 fixes your issue.

thank you so much

**Comment by Romerolweb** [comment]
> 
> 
> Yep, it fixes the issue. Good job!

I have the same problem, and I have 
                "vlucas/phpdotenv": "^4.0",
in my project  (I am using Laravel)

Thanks for your help

**Comment by GrahamCampbell** [comment]
> I have the same problem, and I have

Are you sure you don't actually have invalid syntax in your file. Can you share an example file that doesn't work?
