### ISSUE TITLE
[2.6.0] Adds a breaking change when using single quotted vars

### ISSUE THREAD

**Issue by elliotmoso** [vlucas/phpdotenv#343]
[2.5] foo='{"bar":1}' => parses as foo = {"bar":1}
[2.6] foo='{"bar":1}' => parses as foo = '{"bar":1}'
When using json decode the firsts works fine but when using 2.6 fails with errorno 4 "Malformed JSON"
this added a lot of troubles on our pipeline

**Comment by GrahamCampbell** [comment]
What about 2.6.1 please?

**Comment by GrahamCampbell** [comment]
I'm reasonably sure the latest 2.x and 3.x releases don't suffer this bug. Please let me know if upgrading to 2.6.1 from 2.6.0 doesn't fix your issue.
