### ISSUE TITLE
[Feature Request] envcheck binary to compare env('var') in code against vars set in .env.

### ISSUE THREAD

**Issue by patrickcurl** [vlucas/phpdotenv#346]
you could do something like git grep -orh env\(.* then run some string manipulation to get the vars, and then compare. Could have a special var called ignore_vars='VAR1,VAR2' when it does checks, people could integrate this into their CI flows.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. I don't quite understand what you are asking?
