### ISSUE TITLE
Parser error: "unexpected escape sequence"

### ISSUE THREAD

**Issue by KennedyTedesco** [vlucas/phpdotenv#347]
Hi, there! Migrating from phpdotenv 2.6 to the version 3.3 (because of Laravel 5.8), this var `MYVAR="9VQWPx1%j9QE@kH6mP\Y=V87GL1"`  doesn't parse correctly. Throws this exception:

```
Dotenv\Exception\InvalidFileException: Failed to parse dotenv file due to an unexpected escape sequence.
```

The cause is the backslash `\`. Removing it all works fine, for instance:

```
MYVAR="9VQWPx1%j9QE@kH6mPY=V87GL1"
```

**Comment by GrahamCampbell** [comment]
You need to escape the backslash with another backlash, as of 3.x. In 2.x it may have parsed, or may have crashed with a preg error.

**Comment by GrahamCampbell** [comment]
Please see lines 3 and 4 of the table in the upgrading guide: https://github.com/vlucas/phpdotenv/blob/master/UPGRADING.md. :)

**Comment by KennedyTedesco** [comment]
Sorry, didn't notice that. Thanks! 😄

**Comment by KennedyTedesco** [comment]
Maybe it worth a note about it on Laravel upgrade guide? 🤔
