### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by joeyhub** [vlucas/phpdotenv#348]
When I do:

```
Dotenv\Dotenv::create($dir, 'a.b')->load();
var_dump($_ENV);
```

Nothing happens. _ENV is empty. I get no error messages or anything. Checking the path works and the env is fairly basic, just THING="THANG" entries seprated by \n with trailing \n.

Somewhere you must have an error that's just being ignored.

**Comment by joeyhub** [comment]
The issue is that if it's already set, it'll and you load you just end up with it only in _SERVER and not _ENV.

**Comment by GrahamCampbell** [comment]
What happens when you run this package's test suite on your server please?

**Comment by GrahamCampbell** [comment]
We have tests that check the whole process: https://github.com/vlucas/phpdotenv/blob/master/tests/Dotenv/DotenvTest.php.
