### ISSUE TITLE
Fortify Scan - Path Manipulation at portal/vendor/vlucas/phpdotenv/src/Loader.php, line 163

### ISSUE THREAD

**Issue by AkashGoenka** [vlucas/phpdotenv#358]
Hi,

Thanks a lot for the library, it's verify helpful. This library has come along with the laravel package for us. So we use the Fortify Scan to identify possible vulnerabilities. We have received a vulnerability in this package, the details of which are mentioned below - 

* Allowing user input to control paths used in file system operations could enable an attacker to access or modify otherwise protected system resources. 

At line 163 in file portal/vendor/vlucas/phpdotenv/src/Loader.php,  we have a function - 
protected function readLinesFromFile($filePath){ //some code }. According to the Fortify Scan it would be better if we validate $filePath variable, before performing any sort of file operations. This variable $filePath is also passed in the constructor when the Loader Class is called.

If we could have a way to validate $filePath before it is passed to the other functions of the file, it would help us close this vulnerability. Hence requesting you to llok into the same.

**Comment by GrahamCampbell** [comment]
There is no vulnerability here. The file path should not ever be user provided it. If for some reason you need that, you should validate it yourself.

There is nothing we should do to validate it, since as far as we're concerned, all paths are valid.
