### ISSUE TITLE
Problem with .env variables with backslash

### ISSUE THREAD

**Issue by ybert** [vlucas/phpdotenv#362]
Hello,

I have a Laravel app with a .env that contains :  `DB_DATETIME_UTC='m/d/Y H:i:s\Z'`

It displays this error : 
`The environment file is invalid!
Failed to parse dotenv file due to an unexpected escape sequence. Failed at ['m/d/Y H:i:s\Z'].`

If I remove the backslash it works fine but I need the backslash to be in that variable.

**Comment by GrahamCampbell** [comment]
You'll need to escape the backslash with a backslash. `'m/d/Y H:i:s\\Z'`

**Comment by anibalmorales** [comment]
thanks, it worked very well for me

**Comment by GrahamCampbell** [comment]
Note that in the latest version, escaping backslashes in single quoted strings is not required. Just in unquoted and double quoted strings.

**Comment by parthkharecha** [comment]
1. Use Double Backslashes in Strings
In PHP strings, a single backslash is used as an escape character. To use a literal backslash, you need to escape it by using double backslashes (\\).

Example:
`$path = "C:\\path\\to\\directory";`

2. Use Forward Slashes
PHP can handle forward slashes (/) in file paths on Windows. Using forward slashes can help avoid the issue of escaping backslashes.

Example:
`$path = "C:/path/to/directory";`
