### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by elpanas** [vlucas/phpdotenv#364]
I followed your instructions but i get this error:

> PHP Fatal error:  Uncaught Error: Class 'Dotenv\Dotenv' not found...

I'm on heroku server
I ran "composer require vlucas/phpdotenv"
I've added this on top of my index page
`$dotenv = Dotenv\Dotenv::create(__DIR__);
$dotenv->load();`

It doesn't work anyway. What can i do?

**Comment by GrahamCampbell** [comment]
Could you do the following to help me debug your problem please:

1. Run `composer show` from the same directory you ran the require command.
2. Run `pwd` in that directory, and show me both outputs.
3. Could you then put the following code just above where you load dotenv: `var_dump(get_included_files());`, and show me the output when you run your code.

**Comment by HenonoaH** [comment]
@elpanas Look's like namespace issue. It should be,

```php
$dotenv = \Dotenv\Dotenv::create(__DIR__);
```

Better always try `use`

```php
use Dotenv\Dotenv;

$dotenv = Dotenv::create(__DIR__);
```
