### ISSUE TITLE
Validator Methods

### ISSUE THREAD

**Issue by it-all** [vlucas/phpdotenv#365]
Is there a way to run Validator methods such as notEmpty(), isInteger(), isBoolean(), allowedValues(), etc on environmental variables which are not required? In other words, the variable is not required, but if it exists, it should conform to the validation method.

I have a use case for this, but it doesn't seem possible.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. There is currently no way to do this, you are correct.

**Comment by GrahamCampbell** [comment]
This shouldn't be too hard to implement, however. Did you have something in mind?

Currently, the interface is to call `$dotenv->required(...)->...`. Maybe we should have a different word in place of required, like `ifPresent` or something? Did you have a name in mind?

**Comment by GrahamCampbell** [comment]
I guess we could be dynamic about it, yeh. I just wonder if it isn't clear then that it isn't failing if it's not set.

**Comment by GrahamCampbell** [comment]
Implemented. This will be included in the v3.5.0 release, whenever that goes out.
