### ISSUE TITLE
PHPUnit 8.3.5 + phpdotenv != Love

### ISSUE THREAD

**Issue by alexandrufulop** [vlucas/phpdotenv#373]
Hello,

Regarding this statement:
> By default, Dotenv will NOT overwrite existing environment variables that are already set in the environment.

i have an issue with phpunit.xml env values being overitten by dotenv. 
Can anyone point me into the right direction?

Thanks!

**Comment by GrahamCampbell** [comment]
How are you calling phpdotenv please?

**Comment by alexandrufulop** [comment]
Hi,
Thank you for your reply.
Here it is:
```
    $dotenv = Dotenv::create(__DIR__);
    $dotenv->load();
```

**Comment by GrahamCampbell** [comment]
Hmmm. It's possible PHPUnit is loading its variables after your env code is run.

**Comment by alexandrufulop** [comment]
> Hmmm. It's possible PHPUnit is loading its variables after your env code is run.

Exactly this is NOT happening...

The expected flow: 
1) phpunit properly loads the env variables defined in the phpunit.xml file like so:
```
<php>
         <env name="SOME_ENV" value="test"/>
         ...
</php>
```
2) dotenv is instantiated in my app and loads the .env variables **overwritting** those set by phpunit As i used the load() method and not the override() one, dotenv should not do this...
I tested and if I check for SOME_ENV value before dotenv loads the .env variables, the SOME_ENV returns the proper value as set in phpunit.xml. 
This is why I think that the issue might reside in dotenv...

Thanks for your time!

**Comment by GrahamCampbell** [comment]
Hmm, I guess you should debug the code to see what gets set when.

**Comment by alexandrufulop** [comment]
I did this, as I mentioned before, and it seem that dotenv is overwritting
the existing variables when it shouldn't.

Thanks!

**Comment by GrahamCampbell** [comment]
I meant, the phpdotenv code. :)

**Comment by alexandrufulop** [comment]
Ok. Found the issue.  **Dotenv is loading properly!**
My bad!
In my case dotenv was loaded twice (2 separate instances) and the second time it was overwritting the env variables set in the first place.

Thank you for helping me clear it up!

**Comment by GrahamCampbell** [comment]
Ah, right. Glad you were able to resolve this.

**Comment by alexandrufulop** [comment]
> Ah, right. Glad you were able to resolve this.

I updated the response so it may help other people.
