### ISSUE TITLE
getenv() not working on database.php

### ISSUE THREAD

**Issue by mikelgmh** [vlucas/phpdotenv#375]
Im using Codeigniter. I installed this library, but I am only able to get the enviroment variables from outside the `database.php` file.

For example at `database.php` this **won't work**. It doesn't give any type of error, its just like if there was a blank value.
$db['default'] = array(
	'dsn'	=> '',
	'hostname' => getenv('DB_HOST'),
	'username' => getenv('DB_USERNAME'),
	'password' => getenv('DB_PASSWORD')

);

At login.php, if I do `echo getenv('DB_HOST')` it **will show** the enviroment variable.
Am I missing something?

**Comment by GrahamCampbell** [comment]
I'm not sure. Does codeigniter always load your config files directly, or does it compile them and load that separately, like Laravel does?

**Comment by mikelgmh** [comment]
I don't really know, I'm not sure, but It might load config files directly. This souldn't be a problem, I have seen that some developers used this library too, but I don't know what is going on. I followed [this guide](https://github.com/technoknol/env-in-CodeIgniter).

**Comment by GrahamCampbell** [comment]
I'm not sure. It doesn't look like a bug in the library.

**Comment by ronaldgreeff** [comment]
I was losing it with this issue too. I finally figured it out (it's not an issue with `phpdotenv`, I just want to include for other people seeking help as this is the top link you're directed to). 

In your `.env` file (provided by codeigniter in your project root), you need to uncomment the settings you need (e.g. `database.default.hostname`). Then in your `Database.php`, the corresponding value (in this example "hostname") should be set to an empty string (`'hostname' => '',`).

That's it.

**Comment by mayurmhatre91** [comment]
@mikelgmh  is your issue resolved....i am facing same issue

**Comment by mayurmhatre91** [comment]
@mikelgmh  facing same issue...any resolution ........getting null/empty string in database.php
