### ISSUE TITLE
phpoption/phpoption dependancy license issue

### ISSUE THREAD

**Issue by vanderlee** [vlucas/phpdotenv#381]
phpdotenv requires the `phpoption/phpoption` package, which has an invalid `Apache2` license identifier.

Since that package is no longer actively maintained (or has been so for over 4 years at the moment of writing), it is unlikely they will fix this license identifier. Especially considering they have ignored requests to do so for at least the same number of years.

phpdotenv should look for a replacement if possible.

**Comment by GrahamCampbell** [comment]
> phpdotenv should look for a replacement if possible.

I don't see why? I understand this package is still widely used. We should simply encourage the maintainer to provide a valid license identifier in the composer.json file.

**Comment by GrahamCampbell** [comment]
Indeed, I see the author just merged your PR. :)
