### ISSUE TITLE
Is there precedence set when reading the env variables?

### ISSUE THREAD

**Issue by dingo-d** [vlucas/phpdotenv#382]
I'm not sure if this is related to #39, but I ran into a weird issue where I installed Laravel in my docker container that shares other apps (I know, defeating the purpose of containers, but it's a legacy app so bear with me).
When I tried to connect to the DB it failed even though I had everything correct in my `.env` file. 
Only later did I notice in the error that the password to connect to the DB was wrong. 
Then I checked my `docker-compose.yml` and noticed that I've exported some env variables in the container (with the password that was used to connect to the DB which was wrong).

So it looks like the env variable set in the container has precedence over the one set in `.env` file.

Is there some default chain that is followed when reading the env variables? Kinda like defaultProvider for aws sdk.

**Comment by GrahamCampbell** [comment]
Yes, there is. This is specified in code. By default, if you don't specify, the order is: https://github.com/vlucas/phpdotenv/blob/1bdf24f065975594f6a117f0f1f6cabf1333b156/src/Environment/DotenvFactory.php#L34.

**Comment by dingo-d** [comment]
That explains it 😄Thanks for the explanation 👍
