### ISSUE TITLE
variable with 2 different values

### ISSUE THREAD

**Issue by begueradj** [vlucas/phpdotenv#383]
Hello,
This is not an issue, but a question.

Suppose I have a long **.env** file and, by mistake, I set 2 different values, on 2 different lines, for the same environment variable called` MY_KEY.`  

In this case, when we write : `env(MY_KEY)`, will this library read its first or second value ?

Thank you

**Comment by GrahamCampbell** [comment]
In the latest version of this library, whenever a value occurs more than once in a file, the last occurrence will ultimately be the one that is set.

**Comment by begueradj** [comment]
That makes sens because that imitates the functionality of exporting twice the same variable in an operating system like Ubuntu. Thank you very much for the information @GrahamCampbell
