### ISSUE TITLE
Question: Did the way the phpdotenv loads duplicate keys change?

### ISSUE THREAD

**Issue by jstolp** [vlucas/phpdotenv#386]
It's probably not a bug (i assume it's an undocumented feature)

but previously (i use laravel)

if i define a .ENV with the following values (duplicate key):

```
TEST=first
TEST=last
```

then 

`dd(config("test.test"),env("TEST"));`

the result on laravel 5.7 is "first"

on laravel 5.8 (upgraded _phpdotenv_ version)

this produces "last"

I know duplicate keys are not a thing, but we noticed a change.

**Comment by GrahamCampbell** [comment]
Yes, it did. :)

**Comment by jstolp** [comment]
Thanks! Where did i miss the release notes?

**Comment by GrahamCampbell** [comment]
It actually changed in v3.4.0, and was considered a bug fix, since 3.x was always intended to have that behaviour.

**Comment by jstolp** [comment]
Thanks for the SUPER fast reply! I totally agree, it was a bug.
(Two duplicate keys are not a thing anyway :P )

**Comment by GrahamCampbell** [comment]
The change was made at https://github.com/vlucas/phpdotenv/commit/5084b23845c24dbff8ac6c204290c341e4776c92, if you are interested.
