### ISSUE TITLE
Overriding Apache env variables

### ISSUE THREAD

**Issue by levacic** [vlucas/phpdotenv#39]
So some time ago I had a problem where a certain environment variable was configured in Apache's `<VirtualHost>` block, and `phpdotenv` wasn't overwriting that value with what was configured in the `.env` file.

I use `getenv()` calls in my config files instead of `$_ENV` to simplify handling non-configured values - otherwise I'd have to do something like `array_key_exists($_ENV, 'key')` or something, which is too verbose with no benefit.

The problem with that is, when you have, for example `SetEnv APP_ENV production` in Apache's `<VirtualHost>` block, then the code

```php
putenv('APP_ENV=staging');
echo getenv('APP_ENV');
```

will output `production`.

To successfully override this, PHP's `apache_setenv` function must be called instead, like this:

```php
if (function_exists('apache_setenv'))
{
    apache_setenv('APP_ENV', 'staging');
}
```

The `function_exists()` check must be present so as not to cause errors when the user is not running Apache.

Now of course, this depends on a higher-level decision of whether an Apache-configured environment variable should take precedence over the one specified in a project's `.env` file - and to me it's kind of obvious that it shouldn't, since an `.env` file is a more granular configuration method, and as such, it should take precedence, but of course I may be wrong about that.

Do you think this could/should be included in `phpdotenv`?

---

Also, as an unrelated question (and sorry for hijacking this issue, I just want to avoid spamming issues), is there any reason why you chose to use this specific syntax for `.env` files, other than being similar to Ruby's dotenv syntax? Just plain requiring PHP files (as e.g. Laravel < 5 does) seems to be a much more straightforward approach, which avoids the various issues related to actually parsing the `.env` files, including comments etc. and additionally simplifies generating them, as you can simply `var_export()` an array and be done with it - with the current syntax, it doesn't seem to be as trivial, as one must be careful to correctly escape stuff since the syntax isn't really documented completely (e.g. there's nothing in the docs to explain what to do if I want the literal `{$BASE_DIR}/tmp` as a variable value, without resolving `{$BASE_DIR}` to something else). I'm interested in whether you feel there is any advantage to the current approach over simply doing `$variables = require '/path/to/project/.env.php';` - thanks in advance for your thoughts on this, and sorry for the longish-double-issue.

Thanks for your work, cheers!

**Comment by GabeMedrash** [comment]
Forgive me for reviving a long-dormant issue, but the original issue raised by @levacic regarding Apache env variables is unresolved. Considering the docs claim that Dotenv::overload overrides existing environment variables, I had thought this issue had been solved. The problem, however, is reproducible just as @levacic noted: 

1. `SetEnv FOO bar` in Apache configuration 
2. Set `FOO not_bar` in my project's .env
3. Use `$dotenv->overload();` 
4. `echo getenv(FOO)` => 'bar' (I expect--and want--'not_bar'!)

The solution, as noted, is to check if the `apache_setenv` function exists (and, if you want, check if `apache_getenv` returns truthy), then use `apache_setenv`.

Is there a reason why you wouldn't want to support this feature?
