### ISSUE TITLE
# is removed..

### ISSUE THREAD

**Issue by eunicon** [vlucas/phpdotenv#406]
I using # char for my DB password. I wrote it to .env
(ex, DB_PWD=asdf123!@#)
when I run my program, I faced DB Exception because of # is removed by Parser.processChar() method...

please solve this problem as soon as possible...

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. This is not a bug.

**Comment by GrahamCampbell** [comment]
The hash is used to start a comment. https://github.com/vlucas/phpdotenv#comments. You should enclose your password in single quotes.
