### ISSUE TITLE
php yii2 error

### ISSUE THREAD

**Issue by KichkinaDeveloper** [vlucas/phpdotenv#409]
Fatal error: Uncaught Dotenv\Exception\InvalidPathException: Unable to read the environment file at C:\OSPanel\domains\Arifmetika\.env. in C:\OSPanel\domains\Arifmetika\vendor\vlucas\phpdotenv\src\Loader.php:106 Stack trace: #0 C:\OSPanel\domains\Arifmetika\vendor\vlucas\phpdotenv\src\Loader.php(83): Dotenv\Loader->ensureFileIsReadable() #1 C:\OSPanel\domains\Arifmetika\vendor\vlucas\phpdotenv\src\Dotenv.php(114): Dotenv\Loader->load() #2 C:\OSPanel\domains\Arifmetika\vendor\vlucas\phpdotenv\src\Dotenv.php(52): Dotenv\Dotenv->loadData() #3 C:\OSPanel\domains\Arifmetika\common\config\env.php(6): Dotenv\Dotenv->load() #4 C:\OSPanel\domains\Arifmetika\backend\web\index.php(7): require('C:\\OSPanel\\doma...') #5 {main} thrown in C:\OSPanel\domains\Arifmetika\vendor\vlucas\phpdotenv\src\Loader.php on line 106

**Comment by KichkinaDeveloper** [comment]
I have got some problem? Pls help me, if someone understand it!

**Comment by GrahamCampbell** [comment]
This happens whenever PHP doesn't have permission to read the file, either due to file permissions, or some kind of exclusive lock on the file.
