### ISSUE TITLE
Cant call getenv or $ENV in config.php codeigniter

### ISSUE THREAD

**Issue by bagaskarala** [vlucas/phpdotenv#412]
I'm using this in codeigniter by using hooks and fill hooks.php with this code:
```
# Load phpdotenv
$hook['pre_system'] = function () {
    $dotenv = Dotenv\Dotenv::createImmutable(APPPATH);
    $dotenv->load();
};
```

When i invoke  `getenv('DB_DATABASE')` in database.php it has no problem, 

but when i call from config.php, it is not get called. I set `getenv('BASE_URL')` on $config['base_url'], but when i call base_url(), it return [::1] alias empty

**Comment by GrahamCampbell** [comment]
I guess this is because it loads the config before it does the pre-system hook?

**Comment by bagaskarala** [comment]
> I guess this is because it loads the config before it does the pre-system hook?

i think that too, but how to load env before config.php loaded

**Comment by bagaskarala** [comment]
Oh i've solved my own issue.

So i use this manual installation env package https://github.com/agungjk/phpdotenv-for-codeigniter

It will work everywhere because it load before core codeigniter. But if we use hooks its not work in some places (e.g. config.php) because hooks.php get called after config.php

**Comment by CodeBrauer** [comment]
If you really want to use phpdotenv also in config.php and any other place (except the ENVIRONMENT constant) you can follow these steps:

1. Set `$config['composer_autoload'] = FALSE;` in config.php
2. Make sure your composer files are in /application
3. Paste this before the section `LOAD THE BOOTSTRAP FILE`
```php

/*
 * --------------------------------------------------------------------
 * Composer auto-loading & Dotenv
 * --------------------------------------------------------------------
 *
 * Since the pre_system hook is executed too late there is no other
 * way than to load Composer and Dotenv here
 * 
 * @link https://github.com/vlucas/phpdotenv/issues/412
 * @link https://stackoverflow.com/a/59515340/1990745
 */
require_once APPPATH.'vendor/autoload.php';
$dotenv = Dotenv\Dotenv::createImmutable(FCPATH);
$dotenv->load();

```

**Comment by JoshHighland** [comment]
> If you really want to use phpdotenv also in config.php and any other place (except the ENVIRONMENT constant) you can follow these steps:
> 
> 1. Set `$config['composer_autoload'] = FALSE;` in config.php
> 2. Make sure your composer files are in /application
> 3. Paste this before the section `LOAD THE BOOTSTRAP FILE` in your index.php
> 
> ```
> /*
>  * --------------------------------------------------------------------
>  * Composer auto-loading & Dotenv
>  * --------------------------------------------------------------------
>  *
>  * Since the pre_system hook is executed too late there is no other
>  * way than to load Composer and Dotenv here
>  * 
>  * @link https://github.com/vlucas/phpdotenv/issues/412
>  * @link https://stackoverflow.com/a/59515340/1990745
>  */
> require_once APPPATH.'vendor/autoload.php';
> $dotenv = Dotenv\Dotenv::createImmutable(FCPATH);
> $dotenv->load();
> ```

AWESOME! This worked for me. 

I host on Heroku, so I can only do this on my dev tier. Heroku uses ENV vars from their dashboard.

I wrapped this code in a conditional for the CI_ENV = 'development' and it works great.

For testing and production environments I leave the composer_autoload on
