### ISSUE TITLE
Ambiguous class resolution when generating optimized autoload files

### ISSUE THREAD

**Issue by gael-ian** [vlucas/phpdotenv#416]
Hello,

When generating optimized autoloaders with Composer for the new v4.1.2, Composer raise a long list of warnings about ambiguous class resolution:

```
Warning: Ambiguous class resolution, "Dotenv\Dotenv" was found in both "vendor/vlucas/phpdotenv/src/Dotenv.php" and "vendor/vlucas/phpdotenv/src/src/Dotenv.php", the first will be used.
```

I did not check but I'm pretty sure there's a warning for every file in `src`. v4.1.1 does not raise any of these so I think something went wrong while packaging the latest release.

**Comment by GrahamCampbell** [comment]
Looks like a composer bug. Delete your vendor folder, then run `composer install` again.

**Comment by GrahamCampbell** [comment]
As you can see from the diff (https://github.com/vlucas/phpdotenv/compare/v4.1.1...v4.1.2), there's nothing that changed here that would cause this.

**Comment by gael-ian** [comment]
> Delete your vendor folder, then run `composer install` again.

This solved the problem. Thanks!
