### ISSUE TITLE
Immutable loading of multiples files not really immutable

### ISSUE THREAD

**Issue by netiul** [vlucas/phpdotenv#417]
When an immutable Dotenv loads multiple files with shortCircuit mode = false. Values of files loaded _later_ still overwrite values from _previously_ loaded files.

Considering this situation is not covered by a test (at least I couldn't find one), it seems to me this is an overlooked use case?

Arguably a previously loaded value should be considered an already existing ENV variable.

The code in question is the if-statement at AbstractRepository:L82: https://github.com/vlucas/phpdotenv/blob/master/src/Repository/AbstractRepository.php#L82

```php
public function set($name, $value = null)
{
  {...}

    // Don't overwrite existing environment variables if we're immutable
    // Ruby's dotenv does this with `ENV[key] ||= value`.
    if ($this->immutable && $this->get($name) !== null && $this->loaded->get($name)->isEmpty()) {
        return;
    }

    $this->setInternal($name, $value);
    $this->loaded->set($name, '');
}
```

The 3rd condition `$this->loaded->get($name)->isEmpty()` evaluates to `false`, resulting in the previously loaded value being overwritten even though the first 2 conditions `this->immutable` and  `$this->get($name) !== null` evaluate to `true`.

What exactly is the 3rd condition for?

**Comment by GrahamCampbell** [comment]
Yeh, this is the expected behaviour. Immutable means that variables set before phpdotenv gets started will not be overrwitten. Disabling short circuiting means that phpdotenv concats all the dotenv files together first, then reads them as one file.

**Comment by GrahamCampbell** [comment]
Actually, the behaviour you are asking for can be done by reversing the order of searching you give to phpdotenv?

**Comment by netiul** [comment]
Ah, from the as-one-file-being-loaded point of view I understand the behaviour and it makes sense. Then reversing the file order would indeed fix the issue. That this behaviour is intended is not quite clear though when reading the mentioned code/tests.

Thanks! /close

**Comment by GrahamCampbell** [comment]
Yeh, I am still looking for a better name for this than "immutable", for the v5 release.
