### ISSUE TITLE
Uncaught Error: Class 'Dotenv\\Environment\\Adapter\\EnvConstAdapter' not found

### ISSUE THREAD

**Issue by HenonoaH** [vlucas/phpdotenv#429]
Getting this issue after upgrading to release `4.1.3` I load my dotenv variables like below,

```php
$dotenv = \Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();
```
I'm wondering what might be the issue! Is it configuration changes?

Composer show result,

![image (1)](https://user-images.githubusercontent.com/32451863/78030969-81dd6600-7380-11ea-8fee-c5a3c4ba0b4b.png)

Error log for reference,

![image](https://user-images.githubusercontent.com/32451863/78030171-4e4e0c00-737f-11ea-89dc-7c124dd33238.png)

**Comment by GrahamCampbell** [comment]
This is because you have installed a version of phpdotenv that is not compatible with the version of illuminate/support you have. I assume you have illuminatea/support 6.x, which only works with phpdotenv 3.x: https://github.com/illuminate/support/blob/6.x/composer.json#L46. Either upgrade to illuminate/support 7.x or downgrade to phpdotenv 3.x. ;)

**Comment by HenonoaH** [comment]
@GrahamCampbell Thanks, man. Got it working.

**Comment by mteall** [comment]
I ran into this same issue.  I think this issue could be avoided by listing illuminate/support (with version range) as a dependency in composer?

**Comment by GrahamCampbell** [comment]
No, because there are valid reasons why someone would wanna use illumninate/support without dotenv, and use dotenv with some other package for unrelated reasons.

**Comment by GrahamCampbell** [comment]
People need to read the output composer spits out in the suggest list. :)

**Comment by mteall** [comment]
Thank you for clarifying.  The repo I am working on both includes both illuminate/database (which also brings in illuminate/support) and vlucas/phpdotenv.  They were added long before I was involved so I didn't see suggestions output, but I do see it on the illuminate/support page in packagist now that you mention it.
