### ISSUE TITLE
something need help for chinese string

### ISSUE THREAD

**Issue by krissss** [vlucas/phpdotenv#433]
in `.env` file

```
A="敬请谅解！"
B="敬请谅解"
C="解！"
D="谅解！"
```

use function `getenv()`: A and D return false、B and C return right string
use `$_ENV`, A、B、C、D all right

I known this may cause by `getenv()` "safe" mode, can you give me some suggest to avoid this?

**Comment by GrahamCampbell** [comment]
Do not use the `getenv` function to read environment variables. The correct place to read them from is actually the `$_SERVER` superglobal. PHP did a terrible job of naming...

If you see any package code using `getenv`, please send them a PR to correct their mistake.

**Comment by GrahamCampbell** [comment]
Aside from `getenv` not supporting unicode strings, it is also not threadsafe...
