### ISSUE TITLE
Class Dotenv/DotEnv not found on version 2.6.4

### ISSUE THREAD

**Issue by mariosvasiliou** [vlucas/phpdotenv#434]
Hello guys,
After updating my laravel application it broke the environment.php file loading.
If i revert version to 2.6.3 it works.
Using laravel 5.5.49 and php 7.2.29

`PHP Fatal error:  Uncaught Error: Class 'Dotenv\Dotenv' not found in bootstrap/environment.php:72`

**Comment by GrahamCampbell** [comment]
Clear your composer cache and vendor and try again. The file is still there: https://github.com/vlucas/phpdotenv/compare/v2.6.3...v2.6.4.

**Comment by mariosvasiliou** [comment]
Hey @GrahamCampbell 
Thanks for the quick reply.
I have clear all the files and cache via commands and manually to make sure ;) 
I know that file is there because I have navigated in vendor files .. 
For some reason is not recognized in my environment file after the update but if I revert to v2.6.3 is OK
I am loading dynamically my env file... and i pass the filepath and filename manually if that helps
`  $dotenv = new Dotenv(base_path().DIRECTORY_SEPARATOR, $file);
        $dotenv->overload();`

**Comment by GrahamCampbell** [comment]
> I have clear all the files and cache via commands and manually to make sure ;)

**Comment by GrahamCampbell** [comment]
> I have clear all the files and cache via commands and manually to make sure ;)

You need to actually delete composer's cache directory.

**Comment by GrahamCampbell** [comment]
>I know that file is there because I have navigated in vendor files ..

> PHP Fatal error: Uncaught Error: Class 'Dotenv\Dotenv' not found in bootstrap/environment.php:72

PHP does not agree. Also, there is no environment.php file in laravel apps?

**Comment by mariosvasiliou** [comment]
I have cleared anything...
Yes, you are right, I am loading a custom env file names based on various checks and i require different variables base on selection... 
I'm loading my environment.php in bootstrap/app.php after all singletons are initiated...but this was working before... or if I revert to the previous version. I never had an issue...

**Comment by GrahamCampbell** [comment]
Well, there's nothing I can do. Literally **nothing changed** between the two versions, I said: v2.6.3...v2.6.4.

**Comment by mariosvasiliou** [comment]
Yes I know I have checked the changed files before even post here and looks odd because nothing changed in that files that could lead to this error..not even v2.6.3 ...but I thought that will be good to report it if anyone else has the same issue.
Thanks anyway.
Keep up the good work.
