### ISSUE TITLE
Performance degradation in v4 and v3

### ISSUE THREAD

**Issue by gornostal** [vlucas/phpdotenv#438]
I've upgraded to v4 and noticed a significant performance degradation. I'm running PHP 5.6
Results that I found:
* v4 (latest) has the worst performance -- over 5.6 seconds mean time
* v3 not as bad, but 29% worse than v2 -- 670ms mean time
* v2 has the best performance -- 520ms mean time

This is all info I can give you. Unfortunately I cannot provide a test suite for you.
This ticket is just FYI. You may or may not want to act upon it. Up to you.

Cheers!

P.S. time in seconds is just for comparison. Of course my endpoints do much more than just read the env vars.

**Comment by GrahamCampbell** [comment]
> This is all info I can give you.

If I can't ask followup questions, then I will have to close this, I'm afraid.
