### ISSUE TITLE
Multibyte String support on ^3.3 please

### ISSUE THREAD

**Issue by breeze-ev** [vlucas/phpdotenv#439]
.env Including part of Chinese will report error, example:

`ADMIN_NAME=行内支付`

> Failed to parse dotenv file due to unexpected whitespace. Failed at [行内支付].

 in Dotenv\Parser line 108

`return array_reduce(str_split($value), function ($data, $char) use ($value) {`

<img width="235" alt="image" src="https://user-images.githubusercontent.com/13219988/82630466-59a61100-9c25-11ea-9081-2d790d9359ae.png">

use mb_* prefix function can fixed

`return array_reduce(mb_str_split($value), function ($data, $char) use ($value) {`

> While there are many languages in which every necessary character can be represented by a one-to-one mapping to an 8-bit value, there are also several languages which require so many characters for written communication that they cannot be contained within the range a mere byte can code (A byte is made up of eight bits. Each bit can contain only two distinct values, one or zero. Because of this, a byte can only represent 256 unique values (two to the power of eight)). Multibyte character encoding schemes were developed to express more than 256 characters in the regular bytewise coding system.
>
> When you manipulate (trim, split, splice, etc.) strings encoded in a multibyte encoding, you need to use special functions since two or more consecutive bytes may represent a single character in such encoding schemes. Otherwise, if you apply a non-multibyte-aware string function to the string, it probably fails to detect the beginning or ending of the multibyte character and ends up with a corrupted garbage string that most likely loses its original meaning.
see [https://www.php.net/manual/en/book.mbstring.php](https://www.php.net/manual/en/book.mbstring.php)

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. I think I'm going to consider this a feature request, since we don't have any tests for multibyte strings and don't claim to support them in the README.

**Comment by GrahamCampbell** [comment]
5.0.0 will be released in June. You can install it now with `^5.0@dev`.

**Comment by breeze-ev** [comment]
Thank you so much
