### ISSUE TITLE
Different env file per Environment 

### ISSUE THREAD

**Issue by adrianrios25** [vlucas/phpdotenv#443]
How can I use different .env file per environment like for database configuration and the other configuration. Example : .env.development, .env.testing, .env.production.

**Comment by adrianrios25** [comment]
Managed to find a solution find changing the StoreBuilder/make with the following code:

`/**
     * Creates a new store instance.
     *
     * @return \Dotenv\Store\StoreInterface
     */
    public function make()
    {
        $file = '.env';
        if(defined('ENVIRONMENT')){
            $file = '.env.'.ENVIRONMENT;
        }

        return new FileStore(
            Paths::filePaths($this->paths, $this->names === null ? [$file] : $this->names),
            $this->shortCircuit
        );
    }`

This is useful for CI/CD with Docker Integration‎

**Comment by GrahamCampbell** [comment]
The store builder will be final in v5, and cannot be edited or extended. You should not need to edit or extend any classes of phpdotenv to customise things. The codebase was specifically designed to be compositional.

**Comment by GrahamCampbell** [comment]
Why can't you just pass a name to `createImmutable` or whatever method you are calling to create the phpdotenv instance: https://github.com/vlucas/phpdotenv/blob/v4.1.6/src/Dotenv.php#L89-L103.

**Comment by oytuntez** [comment]
One thing I noticed, this is throwing exception if one of the files in the list doesn't exist, even though this error is suppressed via `@file_get_contents`.

If we relax this a bit, it can help a more straightforward hierarchy.
