### ISSUE TITLE
Dependency Error

### ISSUE THREAD

**Issue by ValentinaRodrigues** [vlucas/phpdotenv#444]
`Fatal error: require(): Failed opening required '/vendor/composer/../jetbrains/phpstorm-stubs/PhpStormStubsMap.php' (include_path='.:/usr/local/Cellar/php@7.2/7.2.31/share/php@7.2/pear') in /vendor/composer/autoload_real.php on line 69`

I get this error when running
`composer require vlucas/phpdotenv`

**PHP Version:** PHP 7.2.31
**Composer version:** 1.10.6

**Solution:**
I tried the following and it worked.
 `composer require jetbrains/phpstorm-stubs:dev-master`

**Comment by GrahamCampbell** [comment]
This looks like an issue with your local environment, and not this package.
