### ISSUE TITLE
quotes detected

### ISSUE THREAD

**Issue by sunuazizrahayu** [vlucas/phpdotenv#445]
i have variable like this: `MY_VAR="blabla bla"`
when i used `echo getenv('MY_VAR');` , it print `"blabla bla"`.

how to get `blabla bla` without quotes? this problem show when i use docker.
i use image `php:7.3-fpm-alpine`

thank you

**Comment by GrahamCampbell** [comment]
No it won't?

**Comment by GrahamCampbell** [comment]
Evidence:

<img width="622" alt="image" src="https://user-images.githubusercontent.com/2829600/83618060-d7511180-a581-11ea-9bf2-006de53d59fe.png">

<img width="458" alt="image" src="https://user-images.githubusercontent.com/2829600/83618085-dfa94c80-a581-11ea-82fe-521dc0b34e05.png">

**Comment by sunuazizrahayu** [comment]
i just know that if using docker i don't need quote on .env when i have whitespace.

so i set my .env like this:
```MY_VAR=blabla bla```

thank you,

**Comment by GrahamCampbell** [comment]
We don't support that syntax, on purpose.
