### ISSUE TITLE
Question: How can I use phpdotenv without use of composer?

### ISSUE THREAD

**Issue by Vishal1107** [vlucas/phpdotenv#450]
**phpdotenv without Composer**

1.  I am working on PHP project and I want to  hide my firebase and google recaptcha keys also I want to hide PHPMailer Username and password for project.

2.  So Is there any way to use phpdotenv without using or installing composer?

3. I am using PHP Mailer Library for my project without composer using autoload file so Like PHPMailer Library can we use phpdotenv library in my project?

**Comment by GrahamCampbell** [comment]
No (at least not easily, and it wouldn't make sense to), however this doesn't mean you need to run composer on deployment. You can just use composer to download your dependencies, and then commit them to your codebase.

**Comment by Vishal1107** [comment]
Thank You so much
