### ISSUE TITLE
Uncaught Error: Class 'PhpOption\None' not found in ..../EnvConstAdapter.php:33

### ISSUE THREAD

**Issue by CruiseLee-ZH** [vlucas/phpdotenv#452]
Hi,

By transferring my Laravel7 project to another shared host, I had some trouble with the composer, i.e. composer.phar. By installing it via ssh I got an Fatal Error. 
Can you help me with following problem:
![image_utz6zh](https://user-images.githubusercontent.com/68335955/87552565-25455300-c6b2-11ea-95a9-86012faa24cf.png)

What does it mean. Where I have to fix it? 

Thank you very much for your helps!

Best regards, Cruise Lee

**Comment by GrahamCampbell** [comment]
It looks like your composer install failed. It's not related to this package. :)

**Comment by GrahamCampbell** [comment]
I'd recommend asking around on some forums if you are unable to solve this on your own. Alternatively, I can provide some paid support. Just let me know.

**Comment by CruiseLee-ZH** [comment]
Ok, thank you. I will come back to you... I try further to solve it by my own for more learning effects.

**Comment by GrahamCampbell** [comment]
@CruiseLee-ZH Were you able to get to the bottom of this?
