### ISSUE TITLE
getenv method returning false

### ISSUE THREAD

**Issue by qwertynik** [vlucas/phpdotenv#454]
```php
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

var_dump($_ENV['TOKEN']); //prints the token from the .env file
var_dump(getenv('TOKEN'));//returns false
```

Are there some additional steps to be taken to get `getenv` working?

**Comment by qwertynik** [comment]
@GrahamCampbell

**Comment by GrahamCampbell** [comment]
Please see https://github.com/vlucas/phpdotenv#putenv-and-getenv. :)

**Comment by GrahamCampbell** [comment]
Using `getenv` and `putenv` is a very bad idea unless your app is just a cli app. php-fpm can leak variables between websites and/or variables become randomly unset.

**Comment by qwertynik** [comment]
Understood thanks @GrahamCampbell for the insight. 
Your empathy is worth appreciation.

**Comment by avdv** [comment]
Hi.

> Using `getenv` and `putenv` is a very bad idea unless your app is just a cli app. php-fpm can leak variables between websites and/or variables become randomly unset.

I am experiencing the latter issue, but even when *not* using getenv.

Details: I am using Apache's mod_php module (this is not php-fpm right?) and I am using version 5.3.0 of  vlucas/phpdotenv loading my `.env` file with `createUnsafeImmutable` - just in case. Some requests are totally fine, but some just don't have the variables set at all. My project is based on Symfony 3 and I am using the Apache mpm event module.

The code checks for a variable that is defined in the env file with `isset($_SERVER['DATABASE_URL'])`.

Does that ring a bell to anyone? Any pointers? TIA!
