### ISSUE TITLE
One .env to rule them all

### ISSUE THREAD

**Issue by antonioribeiro** [vlucas/phpdotenv#455]
Managing several '.env' files plus a '.env.example' is sometimes complicated, and frequently we get some of those files out of sync.

So, it could be a nice feature to be able to use a single `.env` file for all environments, by just hinting environments like:

```pascal
DB_CONNECTION=pgsql // default, not found, or simply the same on all environments

DB_HOST.local=127.0.0.1
DB_HOST.testing=postgres
DB_HOST.staging=10.0.0.2
DB_HOST.production=172.17.0.101
```

And, of course, way of loading for loading the current environment:

```php
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load('production');
```

**Comment by hakuno** [comment]
It seems a limitation.

The basic parser for INI can read this

```
[FAILOVER]
NODE[]=8.8.8.8:80,443
NODE[]=1.1.1.1:80,443

[HEALTHCHECK]
INTERVAL=15000
TIMEOUT=3
RETRY=3
```

with `parse_ini_file(".env", true, INI_SCANNER_TYPED);` 

So I can have grouping & arrays with complete happiness.

But we can do the same with dot-env. Does it?

It seems interesting having a **dot notation** feature.

So we can retrieve with `staging.db_host` (or `db_host.staging` as said).

+1 for dot notation 👍 

ps. It sounds like the `config` helper of Laravel as such.

**Comment by GrahamCampbell** [comment]
I am going to defer the decision of whether this is wanted to @taylorotwell and @jbrooksuk, if your use case is purely Forge.

**Comment by selcukcukur** [comment]
This seems unlikely to be a correct use. @antonioribeiro

**Comment by antonioribeiro** [comment]
@GrahamCampbell , I keep hearing this, but the "use case" argument for denying something is not the best for a community as big as PHP or Laravel, because, the bigger the community the nearest from **infinity** "use cases" can get.

My use case is not your use case and will probably not be from thousands of other developers. My use case can also change according to the client I'm working for or the infrastructure I'm deploying. Have you tried to update a bunch of `.env` keys on an Azure App Service? It's a nightmare! Our last app is being deployed to it, we have dozens of keys, and the only way to do it in bulk is to update a JSON file like this:

![image](https://user-images.githubusercontent.com/3182864/94345930-8e8a0080-0029-11eb-9915-a23bb8a24b1e.png)

This one has 640 lines * 3 environments = 1920 lines, I broke this JSON several times, I also pasted the wrong keys to the wrong environment, because, yes, I'm not good doing boring repeating tasks.

So maybe the **use case is reducing repetition and human errors**?

Otherwise you have to click to edit one-by-one. But they are super secure, so it would not be a big security problem to have the keys for all 3 clusters in a single JSON file. The amount of errors I make would drop considerably, because, yes, I'm not good doing boring repeating tasks.
 
The real **use case here is namespacing the `.env` file**. 

Forge was just an example, and Forge, as far as I can tell is just a server provisioning boxes supporting natively only a few services, but the use case is any server, any box, any service deploying Laravel apps, on AWS,  Azure, Google Cloud, Docker, Kubernettes, Linode, Vultr, Scaleway, DigitalOcean, OVH, Alibaba... managed by Forge or anything else, and believe me, there are a lot of other dashboards doing the same out there, and many of those services have their own deployment and app management systems too.

**Comment by hakuno** [comment]
@antonioribeiro I guess you need to overcome this limitation and look for some DevOps approach. I'm unsure how much the staff want to increment one new feature like that. Unless you've a ready PR for review.

Ps. Actually, those settings are related to many environments (in your use case closely). If you set all environments rather than current one, so it becomes a configuration instead of environment variables.

**Comment by GrahamCampbell** [comment]
PHPDotenv already natively supports loading more than one file. Why can't you just load a base file and then a file specific to the environment you have?

**Comment by XaeroDegreaz** [comment]
@antonioribeiro - Could you possibly use something like `array_merge` to do what you want? Load your default file, then load another for a different environment, and merge the arrays while overwriting keys (where necessary)? It may be a stop-gap measure if there isn't going to be official support for it.

**Comment by dobryak** [comment]
@antonioribeiro - I think GNU Make can help you solve the problem.

Makefile:  
```make
.env: .env.example
    @./scripts/update_env
```

then just: 
```sh
$ make
```

So, you can keep your .env file updated.

**Comment by nahiyan** [comment]
Can they consider using TOML for configuration files?  The configuration files, especially for Laravel, would be so much cleaner!

**Comment by frob** [comment]
Sounds more like you don't want to use .env files for things. Also, not really understanding how your wouldn't need to edit the values in all the places if a file was changed or a field added.

**Comment by GrahamCampbell** [comment]
I'm going to close this out for now as out of scope of what the package was intended to do.
