### ISSUE TITLE
 Uncaught Error: Call to private Dotenv\Repository\Adapter\EnvConstAdapter::__construct() from context 'Illuminate\Support\Env'

### ISSUE THREAD

**Issue by notflip** [vlucas/phpdotenv#458]
This is the full error I'm receiving
` Uncaught Error: Call to private Dotenv\Repository\Adapter\EnvConstAdapter::__construct() from context 'Illuminate\Support\Env' in /var/www/vendor/illuminate/support/Env.php:58`

I have a project using slim (it's not a laravel project), where I have a `public/index.php` file that has the following piece of code

```
require_once __DIR__ . '/../vendor/autoload.php';

$dotenv = Dotenv\Dotenv::create(__DIR__ . '/..');
$dotenv->load();
```

So I go up one folder since my index.php file is in the public folder.
Am I missing something?
Thank you

**Comment by GrahamCampbell** [comment]
This can only happen if you have an incompatible version of illuminate support and dotenv.

**Comment by GrahamCampbell** [comment]
If you have Laravel 8 components, you need `^5.2` of this package, and if you have Laravel 7 components, you need `^4.1`.

**Comment by GrahamCampbell** [comment]
Or Laravel 6 LTS needs `^3.3`.

**Comment by notflip** [comment]
@GrahamCampbell  I'm not using Laravel at all, does this package work with just vanilla php? (or slim framework, the one I'm using)

**Comment by mfn** [comment]
> I'm not using Laravel at all

![image](https://user-images.githubusercontent.com/87493/93423950-624ae300-f8b7-11ea-8572-5e1dc6d26d4b.png)

But it seems you, or something, is at least a Laravel component which is incompatible (i.e. outdated).

**Comment by notflip** [comment]
Right, Good point let me see who included Illuminate, and as @GrahamCampbell  said I'll match the correct version of this package. Thanks!
