### ISSUE TITLE
Apache Config Issue

### ISSUE THREAD

**Issue by RiversideRocks** [vlucas/phpdotenv#461]
Hello! I've blocked access to the .env file on the internet with apache2, only issue is that breaks the package. How could I fix that?

**Comment by GrahamCampbell** [comment]
I don't follow?

**Comment by RiversideRocks** [comment]
I used my .htaccess file to block access to the .env file on the internet.

The package can no longer read the .env file.

**Comment by GrahamCampbell** [comment]
That doesn't seem related. You probably also changed the file permissions. In any case, this is not a bug with this package. If you'd like to purchase some paid support to resolve the issue with your server, my rates are $50/hour. Let me know.
