### ISSUE TITLE
This package isn't meant for production or don't apply anymore?

### ISSUE THREAD

**Issue by naaando** [vlucas/phpdotenv#463]
Hi guys, times have passed that I read this but that doubt never got away, hope someone can help me.

> Also - In the ideal setup, your .env file itself will never be deployed with your project - the idea is that on the production servers, your environment variables will be already loaded and ready to go through some other config method. So really, dotenv itself and the file parsing step should really only ever be done during development.

https://github.com/vlucas/phpdotenv/issues/25#issuecomment-49876501

This was said in 2014, but the README doesn't mention this anywhere, so I believe almost everybody using this library is misled to deploy and set the environment on .env instead. Shouldn't this be advised in the README?

**Comment by GrahamCampbell** [comment]
You should not, in general, be using this package to load `.env` files in web requests, on every request, since this will be kinda slow. As long as you don't use getenv, it is still safe to use in production. Out of the box, the latest version makes it super clear using getenv and putenv is bad idea by calling their usage unsafe (due to leaking variables between apps on the same server!).

Using this package in single-threaded console apps should be totally fine, either way. No variable leakage, and performance isn't such a big deal.

**Comment by naaando** [comment]
Considering that even laravel use this way, this shouldn't be a problem so. Thanks

**Comment by marijnbent** [comment]
@naaando  FYI; Cache your config on Laravel, you shouldn't use env() directly, but config()
https://laravel.com/docs/8.x/configuration#configuration-caching

**Comment by mklepaczewski** [comment]
Just to give some context - I tested it on E5-2620 v3 2.4 GHz / Samsung 980 Pro SSD 1 TB / PHP 7.4 opcache / FPM. I measured performance hit after 1000 requests to allow for various CPU / OS / PHP caches to kick in.

| # of .env files | # of variables | Time in ms |
| :---: | :---: | :---: |
| 1 | 10 | 1.2 - 1.5 ms |
| 1 | 40 | 3 - 3.5 ms |

Sorry, I didn't bother to test more .env files.

Code snippet I used:
```php
$start = microtime(true);
$dotenv = Dotenv::createImmutable(__DIR__ . "/../");
$dotenv->load();
$totalInMs = (microtime(true) - $start) * 1000;
die("It took: $totalInMs ms\n");
```

One needs to decide if it's a lot or not. Most of the time there are probably bigger performance wins to gain, but for - for example - API requests this might be nothing to sneeze at.

I suppose it shouldn't be too hard to write basic cache layer around phpdotenv (e.g. check modification time of all .env files) and use it until you're Facebook.
