### ISSUE TITLE
What about white space?

### ISSUE THREAD

**Issue by tkoop** [vlucas/phpdotenv#474]
I read through the README, looking to see if values are trimmed of white space.  From the fact that there are no spaces around the equals, I could assume that white space is not trimmed (because if there was a space after the equals, it would be the first character of the value).  But from the fact that I saw a comment after a value, I could guess that white space after the value (and before the comment) is trimmed.

Perhaps you could talk about trimming white space, or not, in the README.

**Comment by GrahamCampbell** [comment]
You cannot have whitespace right of the equals sign until you quote the value. This will result in a parse error. If you are ever in doubt of the behaviour, checkout the tests. They are the best documentation! :)

**Comment by GrahamCampbell** [comment]
Yes, whitespace around both names and their values is removed. If the value is quoted, then whitespace inside the quotes is preserved. https://github.com/vlucas/phpdotenv/blob/v5.3.0/src/Parser/EntryParser.php#L73
