### ISSUE TITLE
AdapterInterface not found

### ISSUE THREAD

**Issue by MikeiLL** [vlucas/phpdotenv#475]
On a fresh Ubuntu 20 server, running `php 7.4.15`, using Roots/Bedrock framework and Trellis provision/deploy, I'm getting the following error:

```
'Dotenv\Repository\Adapter\AdapterInterface' not found in /srv/www/example.com/releases/20210228022415/vendor/vlucas/phpdotenv/src/Repository/Ada
pter/ServerConstAdapter.php:10
```

This happens in the Trellis deployment and also when on the server, running (in 20210228022415/):

```
wp core is-installed --skip-plugins --skip-themes
```

Thanks and sorry for the trouble.

**Comment by GrahamCampbell** [comment]
Probably you have the wrong version of phpdotenv installed, or it not installed at all. It's also possible your vendor folder or composer cache is corrupted. You should make sure the phpdotenv version is correct, and also delete your vendor folder and composer cache, then re-run the composer install.

**Comment by MikeiLL** [comment]
Thanks much, Graham. Did that and now getting a db connection error when I try to run `wp core is-installed --skip-plugins --skip-themes`. Will report back once that gets resolved.

**Comment by GrahamCampbell** [comment]
I'm going to close this issue now, since there's no bug with this project. If you need further support, I'd recommend posting on some forums or getting help from a contractor. :)
