### ISSUE TITLE
Escape function

### ISSUE THREAD

**Issue by AidasK** [vlucas/phpdotenv#476]
I would like to write a .env file editor and .env file looks pretty straightforward, but is there a function which creates an escaped value? E.g. encloses string with quotes, if it contains a space or a hashtag. Escapes variables and backslashes. Similarly like htmlentities is used to escape html or escapeshellarg escapes shell argument.

**Comment by AidasK** [comment]
escapeshellarg fn probably does it right, though this output is not developer friendly to edit it afterwards. It adds unnecessary quotes for single string words and boolean variables are represented as empty string or 1.

**Comment by GrahamCampbell** [comment]
You only need to escape double quotes and slashes inside double quotes. That's it. Don't use any fancy functions. Just str_replace double quotes and slashes to escape them.

**Comment by GrahamCampbell** [comment]
The parser is here: https://github.com/vlucas/phpdotenv/blob/v5.3.0/src/Parser/EntryParser.php#L142-L275.

**Comment by GrahamCampbell** [comment]
Writing a correct .env file editor is not straight forward. Correct parsing of comments and multiline has to also be handled. ;)
