### ISSUE TITLE
How do you access absolute path

### ISSUE THREAD

**Issue by otengkwame** [vlucas/phpdotenv#477]
I am working on a project and I need to get the root directory path and other paths to be set in my .env
how do I get this done. I have been searching and I can't find any solution. May be I don't know to do that.

**Comment by ceswebmaster** [comment]
You could use $_SERVER['DOCUMENT_ROOT'] to get your document root and write to your .env file if necessary.

**Comment by GrahamCampbell** [comment]
Yeh. Please ask on some forums. This issue tracker is for bugs in the library. :)
