### ISSUE TITLE
load directly from file as string ?

### ISSUE THREAD

**Issue by allan-simon** [vlucas/phpdotenv#481]
my use case:
I have my php code running on lambda using bref.sh

my .env file is encrypted using AWS's  KMS (i.e symetric encryption)  and the resulting base64 string is then put in a environment variable (so that my CI/CD and provisionning only manipulate this string as an opaque string, and don't need to be updated every single time I add/remove an application environment variable) 

The string is decrypted at runtime and so I got the content of the `.env` file in a string, which I would like to load into DotEnv as if it was a file, is it possible to do so, if not , is it an addition that could be considered ? 

Right now I'm working around the problem by dumping the content first into a temporary file, but that seems a bit hackish

**Comment by GrahamCampbell** [comment]
You can use the StringStore. :)

**Comment by GrahamCampbell** [comment]
```php
$dotenv = new Dotenv\Dotenv(
    new Dotenv\Store\StringStore('YOUR RAW FILE CONTENT HERE'),
    new Dotenv\Parser\Parser(),
    new Dotenv\Loader\Loader(),
    RepositoryBuilder::createWithDefaultAdapters()->make()
);
```

**Comment by allan-simon** [comment]
thanks !
