### ISSUE TITLE
$_ENV and $_SERVER priority

### ISSUE THREAD

**Issue by ddzobov** [vlucas/phpdotenv#482]
Hello

I'm trying to run tests for Laravel application via PHPUnit under docker container with set of env variables.

I want to override some environment variables via PHPUnit:
```
// phpunit.xml
<php>
     <env name="DB_CONNECTION" value="sqlite" force="true" />
</php
```

PHPUnit changes this variable in $_ENV array, but $_SERVER leaves untouched:
```
var_dump($_ENV['DB_CONNECTION']); // string(6) "sqlite"
var_dump($_SERVER['DB_CONNECTION']); // string(5) "pgsql"
var_dump(env('DB_CONNECTION')); // string(5) "pgsql"
var_dump(getenv('DB_CONNECTION')); // string(6) "sqlite"
```

Seems like, $_SERVER have higher priority than $_ENV in phpdotenv package.
Is this normal behavior? 

If yes - can you recommend me something to solve my problem? Thanks.

**Comment by GrahamCampbell** [comment]
> Seems like, $_SERVER have higher priority than $_ENV in phpdotenv package.

Yes, PHP has confusingly named superglobals. `$_SERVER` should be where you go to look for environment variables. Instead of env in phpunit, just write server.

**Comment by GrahamCampbell** [comment]
eg

```
    <php>
        <server name="APP_ENV" value="testing"/>
...
```

**Comment by ddzobov** [comment]
Omg, you saved me, thanks!
