### ISSUE TITLE
Container installation

### ISSUE THREAD

**Issue by dan-burt** [vlucas/phpdotenv#486]
I have been following a MongoDB guide for deploying PHP with MongoDB client / SDK [here](https://developer.mongodb.com/quickstart/php-setup/). In this guide, they use your `composer` package.

However, I would like to place this into a Docker container, and was able to get the `mongodb/mongodb` package installed by replacing the `__DIR__` location and hardcoding in a full path to "/usr/bin/vendor/autoload.php" in a PHP page's `require_once` directive. I simply appended the installation of PHPDotEnv to this same `composer` command:
`RUN cd /usr/bin && composer require mongodb/mongodb vlucas/phpdotenv`

I rebuilt the Dockerfile and uploaded to Docker Hub, which was successful, as redswitch/php-mongodb

Now on 1st run, I cannot load the package. I have tried both these commands but errors same each time:
`$dotenv = Dotenv\Dotenv::createImmutable("/usr/bin");`
`$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);`

To load the `mongodb` package, I use:
`require_once '/usr/bin/vendor/autoload.php';`

(As opposed to `__DIR__ . '/vendor/autoload.php';`)

My docker-compose.yml moves the `/var/www/html/` directory to the same directory, i.e.:
```
services:
  web:
    image: redswitch/php-mongodb:8.0-1.9.0
    container_name: web
    volumes:
      - ./html:/var/www/html
```

I cannot find any files or folders inside the container matching "Dotenv".

Can I ask for further troubleshooting / assistance please?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Since this is a support request, I'd recommend asking on some forums or emailing me direct if you'd like to buy some paid support.
