### ISSUE TITLE
Cannot read variable from Elastic Beanstalk Console

### ISSUE THREAD

**Issue by ikudosi** [vlucas/phpdotenv#488]
Hello, not entirely sure if this is a DotEnv issue or something else.

I'm using AWS Beanstalk's web console to set environment variables and I'm getting this error `Failed to parse dotenv file. Encountered unexpected whitespace at [S'well B2B]` with the following variable:

![image](https://user-images.githubusercontent.com/5790073/124061999-f37de700-d9fd-11eb-8a2f-e2be60a56ae1.png)

I essentially created my own helper function to use instead of env():

```
function swell_env($key, $default = null) {
        return array_key_exists($key, $_SERVER) ? $_SERVER[$key] : env($key, $default);
}
```

Example:

```'name' => swell_env('APP_NAME', 'S\'well Custom Portal'),```

**Comment by GrahamCampbell** [comment]
Looks like that console must be writing invalid syntax to the env file. You will need to enclose the value in double quotes because it contains both a space and a single quote:

```
APP_NAME="S'well B2B"
```
