### ISSUE TITLE
I get an error when I use an underscore

### ISSUE THREAD

**Issue by 449134904** [vlucas/phpdotenv#489]
Dotenv\Loader\Parser::parse('APP_" while reading response header from upstream, client: 192.168.56.1, server: blt.bendi.com, request: "POST /wxapp.php?i=undefined&t=undefined&v=undefined&from=wxapp&c=entry&a=wxapp&do=index&m=lionfish_comshop&sign=8a0cb5e4e59292e3dc5fd743c84b9c37&controller=index.a HTTP/1.1", upstream: "fastcgi://unix:/dev/shm/php56-cgi.sock:", host: "blt.bendi.com"

**Comment by GrahamCampbell** [comment]
This is not enough information for me to do anything with, sorry.
