### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by GrahamCampbell** [vlucas/phpdotenv#49]
* Create a `1.0` branch from the `master`, and set it as the default branch on github
* Move the `brightmachine-v2` branch to the `master` branch

That way, people can install v2 using `~2.0@dev` as a version constraint.

**Comment by jrobeson** [comment]
so what's going on with this? I see there's an actual 2.0 branch now, but i don't know what happens next.

**Comment by vlucas** [comment]
There is a `2.x-dev` branch in composer you can use to install and use v2.

**Comment by jrobeson** [comment]
i was trying to understand when 2.x will become a release.

**Comment by GrahamCampbell** [comment]
v2 is a bad branch name. It should be 2.0.
