### ISSUE TITLE
Assist users to hide .env file from webroot

### ISSUE THREAD

**Issue by saminiemi** [vlucas/phpdotenv#490]
There should be warnings/suggestion on Readme page that .env file in webroot can be world-readable by default in many server configurations.

According ie. webserver logs or Cloudflare security logs, bots scanning .env files from websites are very used hacking attempt. 

Screenshot from Cloudflare Firewall:
![CleanShot 2021-07-06 at 11 12 04@2x](https://user-images.githubusercontent.com/4686187/124565849-20d9f300-de4b-11eb-99b7-0e67fc75622f.png)

**Comment by GrahamCampbell** [comment]
dotenv files should ideally not be deployed at all, and if they are, they should not be placed in the webroot directory,

**Comment by saminiemi** [comment]
Thanks Graham for clarifying this. 

I strongly suggest to make that clear in README also. For me following arguments encourages to use  dotenv in production:

* NO editing virtual hosts in Apache or Nginx
* NO adding php_value flags to .htaccess files
* EASY portability and sharing of required ENV values
