### ISSUE TITLE
cannot read Nested Variable 

### ISSUE THREAD

**Issue by reactmore** [vlucas/phpdotenv#491]
hi how to use nested varible on latest version ?

dotenv cannot read nested variables in env file after testit

Env File : 
`
BASE_DIR='C:\laragon\www\supportbot'
LOGS_DIR='${TG_BASE_DIR}/logs'
`

PHP file 
`
require_once __DIR__ . '/vendor/autoload.php';
Dotenv::createUnsafeImmutable(__DIR__)->load();

$logging_paths['LOG_DIR'] = getenv('LOGS_DIR');

print_r($logging_paths);
`

Response 
`
array(1) { ["LOG_DIR"]=> string(19) "${TG_BASE_DIR}/logs" }
`

**Comment by GrahamCampbell** [comment]
This is because you are using single quotes instead of double quotes. :)

**Comment by GrahamCampbell** [comment]
```env
BASE_DIR='C:\laragon\www\supportbot'
LOGS_DIR="${TG_BASE_DIR}/logs"
```
