### ISSUE TITLE
Support for Command Substitution

### ISSUE THREAD

**Issue by vicholp** [vlucas/phpdotenv#493]
As far as I know, phpdotenv is a php version of ruby's [dotenv](https://github.com/bkeepers/dotenv), and there you can use `${command}` to set a variable from a command output ([Variable Substitution](https://github.com/bkeepers/dotenv#command-substitution)). 

Why this one does not support that? Is it possible?

**Comment by GrahamCampbell** [comment]
We don't support that, because we don't want to open up the ability for arbitrary code execution. If you need to do this, you can write to the env variables using PHP code. :)
