### ISSUE TITLE
Vars can't load from env file

### ISSUE THREAD

**Issue by artemvolt** [vlucas/phpdotenv#495]
Hello!

Steps for reproduce:
1. composer require vlucas/phpdotenv
2. create env file  (.env) with var:
`DB_DSN="Hello"` 
3. Create index.php

```php
<?php
use Dotenv\Dotenv;

require __DIR__ . '/vendor/autoload.php';

$env = Dotenv::createMutable(__DIR__);
$env->load();

var_dump(getenv('DB_DSN'));
```

I can't see value of var.

I run command by composer (ver 2) in docker container (php 8) on mac.

Can you help me?

**Comment by GrahamCampbell** [comment]
You'll need to enable unsafe mode to use getenv. See https://github.com/vlucas/phpdotenv#putenv-and-getenv. :)

**Comment by GrahamCampbell** [comment]
```php
$env = Dotenv::createUnsafeMutable(__DIR__);
```

**Comment by artemvolt** [comment]
Ou, Thanks!
