### ISSUE TITLE
Silence operator 

### ISSUE THREAD

**Issue by ls5302** [vlucas/phpdotenv#498]
Using the silence operator (@) here:

https://github.com/vlucas/phpdotenv/blob/master/src/Store/File/Reader.php#L73

causes problem on Heroku as I believe it is either disabled or behaves differently in PHP 8.0.

If think it would be better to use file_exists.

**Comment by GrahamCampbell** [comment]
File exists is no good because we'd just be introducing a race condition, and reading the file could still fail for a reason other than "does not exist". It sounds rather like you have an error handler set up and you are not checking to see if the error was silenced before handling it?

**Comment by GrahamCampbell** [comment]
Closing this, since in that link, they actually give an example of silencing errors from IO as a valid and intended use case of this operator, just like we're using it for. :)

**Comment by ls5302** [comment]
Thank you for the reply. I couldn't make it work on Heroku, and I'm not sure I follow your reasoning for using the operator. `is_readable` might be better but I suppose the file could still be deleted after the check. The original Ruby code appears to ignore nonexistent file. The symfony implementation of a similar library throws an error if the file doesn't exists which IMO is more transparent. Decided to use `symfony/dotenv` instead, even though I have to handle the exception.
