### ISSUE TITLE
Instalar sin composer

### ISSUE THREAD

**Issue by PaolitaGalarza** [vlucas/phpdotenv#499]
Lo sé!... es absurdo que no quiera utilizar composer. Tengo mis razones.
Ayudaría mucho que indiquen como instalar phpdotenv sin utilizar composer, por ejemplo la librería de phpmailer en su documentación en forma muy breve lo explica. 
Alguna orientación, estaré siempre agradecida.

**Comment by GrahamCampbell** [comment]
Sorry, I can't process non-English tickets.
