### ISSUE TITLE
Impact on performance

### ISSUE THREAD

**Issue by multispace88** [vlucas/phpdotenv#502]
I noticed that loading phpdotenv via
```
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->safeLoad();
```
slows down PHP execution quite a bit.

With a simple "hello world" test, I noticed an execution time of **~47ms** when not loading the .env variables.
When the code mentioned above was added to that same PHP file, the execution time increased to **~220ms**.
That may not seem like that much, but to keep our API performant, that's an extra hit we cannot take.

Is this a known issue?

**Comment by GrahamCampbell** [comment]
Is that a cold start? Do you have opcache enabled? A good test would be to load an empty file. If it still takes a long time, this tells you not that this library is slow, but that PHP is having to compile a bunch of code on the fly and/or your server is very slow.

**Comment by GrahamCampbell** [comment]
Closing due to no response. Feel free to open a new issue if required.
