### ISSUE TITLE
Misspell in Lexer::lex?

### ISSUE THREAD

**Issue by enikeishik** [vlucas/phpdotenv#503]
Method [Lexer::lex](https://github.com/vlucas/phpdotenv/blob/master/src/Parser/Lexer.php)

On line 48 defined variable
`$tokens = [];`

May be it means
`$matches = [];`

**Comment by GrahamCampbell** [comment]
Thanks for the report. I don't think this is a typo, but just dead code that can be deleted.

**Comment by GrahamCampbell** [comment]
Fixed.
