### ISSUE TITLE
PHP 8.1 deprecation warning

### ISSUE THREAD

**Issue by scottgruber** [vlucas/phpdotenv#504]
Hi,

I came across an error after updating to PHP 8.1 while loading a via CraftCMS site locally. The same error also happened using PHP8.0. 

[PHPWatch posted a new PHP8.1 attribute `New #[ReturnTypeWillChange] attribute`](https://php.watch/versions/8.1/ReturnTypeWillChange) which may solve the issue. 

Here is the error.

```
Deprecated: Return type of Dotenv\Environment\AbstractVariables::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php on line 162

Deprecated: Return type of Dotenv\Environment\AbstractVariables::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php on line 170

Deprecated: Return type of Dotenv\Environment\AbstractVariables::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php on line 178

Deprecated: Return type of Dotenv\Environment\AbstractVariables::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php on line 186
```

**Before**

```
/**
     * {@inheritdoc}
     */
    public function offsetExists($offset)
    {
        return $this->has($offset);
    }

```

**After**

```
/**
     * {@inheritdoc}
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return $this->has($offset);
    }
```

As a quick test, I took a look in AbstractVariables.php and added `#[\ReturnTypeWillChange]` before the public function declaration and the warning was suppressed. I read your contributing guidelines, and could try to make the changes and submit a PR, but I'm a junior PHP developer and might not code it correctly.

**Comment by estebancastro** [comment]
Same issue here, running CraftCMS locally with Laravel Homestead.

**Comment by GrahamCampbell** [comment]
That version of Laravel does not support PHP 8.1 anyway.

**Comment by GrahamCampbell** [comment]
Ask them to upgrade to a newer version of phpdotenv. :)

**Comment by scottgruber** [comment]
I downgraded too and that resolved fixed the issue for the moment, although I dropped down to php7.4. Too close to the holidays to worry about it.

`valet use php@7.4`
`composer global update`
`valet restart`

**Comment by GrahamCampbell** [comment]
Fixed.

**Comment by Tsdjimmy** [comment]
Install a compatible php version with `brew install php@7.4`

and use it by running 
`Brew link php@7.4`

**Comment by Tsdjimmy** [comment]
> Install a compatible php version with `brew install php@7.4`
> 
> and use it by running `Brew link php@7.4`

THE ABOVE IS FOR MAC USERS

**Comment by GrahamCampbell** [comment]
@Tsdjimmy that is not good advice. You need to instead upgrade to the latest phpdotenv version in the major series you are using. The latest 2.x, 3.x, 4.x and 5.x releases all run on PHP 8.1 without this error.

**Comment by selenearzola** [comment]
[scottgruber](https://github.com/scottgruber) thanks!!

**Comment by GrahamCampbell** [comment]
@selenearzola I re-iterate: it is **not** a good idea to use out of date software. The latest version of each 2.x, 3.x, 4.x and 5.x series package is tested on, and known to work with the latest version of PHP. Do not downgrade PHP to "fix" issues with this package - the real problem is that you mistakenly installed an old version of this package - a common mistake is writing `5.0` instead of `^5.0` - check your `composer.json` file.
