### ISSUE TITLE
some regex are not accepted

### ISSUE THREAD

**Issue by med-ezzairi** [vlucas/phpdotenv#508]
I have in my .env file (used with Laravel version 8.81.0) the following string which is not accepted.

.env file

`VALIDATOR_RULE_TEL="/^(0)([5-8])\d{8}$/"`

php artisan -V shows:

```
The environment file is invalid!
Failed to parse dotenv file. Encountered an unexpected escape sequence at ["/^(0)([5-8])\d{8}$/"].
```

Any suggestion please!

**Comment by GrahamCampbell** [comment]
You need to escape your `\` character. `VALIDATOR_RULE_TEL="/^(0)([5-8])\\d{8}$/"`. Alternatively, you can use single quotes `VALIDATOR_RULE_TEL='/^(0)([5-8])\d{8}$/'`.
