### ISSUE TITLE
Change ignored

### ISSUE THREAD

**Issue by milosb793** [vlucas/phpdotenv#511]
Hey all,

I'm having some weird issue, when I change the variable in `.env` file from one value to another, it doesn't get updated. When I add a new variable, it gets recongized. Is there any caching or what? 

I'm having one main module which has a default .env file, and submodules, having their own .env which can override variables from the main module. Here's a code sample: 

```php
<?php

use ActiveRecord\Config;

$dotenv = \Dotenv\Dotenv::createMutable(__DIR__, null, false);
$dotenv->load();
```

**Comment by GrahamCampbell** [comment]
Are you using `getenv` to read the variable?

**Comment by milosb793** [comment]
Yes, exactly

**Comment by GrahamCampbell** [comment]
Then you either need to use unsafe mode or change your code to read from `$_SERVER`, instead. `getenv` is not suitable for use on php-fpm, because it is not thread safe, so may leak variables from other apps on the same server, or return null.

**Comment by GrahamCampbell** [comment]
See https://github.com/vlucas/phpdotenv#putenv-and-getenv.
