### ISSUE TITLE
Dotenv\Dotenv::createImmutable(__DIR__, $env_file) doesn't work in a 2.5.2 version

### ISSUE THREAD

**Issue by Jameskirkland1** [vlucas/phpdotenv#512]
I am maintaining an old system in which the PHP version is about 5.5, so I can only install the phpdotenv 2.5.2 version.

then I found the code block doesn't work.( it works when I use a higher phpdotenv version with higher php version in other testing environment)

    $dotenv = Dotenv\Dotenv::createImmutable(__DIR__, $env_file);
    $dotenv->load();   // safeLoad()  also doesn't work
    $variable = $_ENV['XXXXXX']

Please give me some instructions or give me a simple example to tell me how the phpdotenv initilization and calling should be when I have to use the phpdotenv 2.5.2 version.

Thank a lot.

**Comment by GrahamCampbell** [comment]
[v4.2.2](https://github.com/vlucas/phpdotenv/releases/tag/v4.2.2) is the newest version that works on PHP 5.5. I'd recommend upgrading to that. If you need additional support or are not able to upgrade, ping me at `hello at gjcampbell.co.uk`, and we can book in some paid consulting time. :)

**Comment by Jameskirkland1** [comment]
@GrahamCampbell Thank you very much. will contact you soon. best regards.
