### ISSUE TITLE
Is there a way to make a new environment from a existing one?

### ISSUE THREAD

**Issue by ap-coder** [vlucas/phpdotenv#513]
What I mean is there a way to make a new env say testing with the same settings as development environment?  Just wondering

**Comment by GrahamCampbell** [comment]
I don't understand the question.

**Comment by jaetooledev** [comment]
@ap-coder Do you mean have a seperate .env file for testing?

If so, and you are using PHPUnit for your testing, you can create a file called .env.testing and load that in your phpunit.xml file to be used for tests. Just remember not to commit any secrets to your code base!
