### ISSUE TITLE
Existing variable is missing

### ISSUE THREAD

**Issue by marioquartz** [vlucas/phpdotenv#514]
Using PHP 7.4
Version 5.4.1

.env file contains only `BASE_URL=""`

Test code
```php
include __DIR__ . "/vendor/autoload.php";

try {
    $dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
    $dotenv->required(["BASE_URL"]);
    $dotenv->load();
    var_dump(getenv("BASE_URL"));
} catch (Exception|Error $e) {
    echo $e->getMessage();
}
```
But there are an exception and this is the message "One or more environment variables failed assertions: BASE_URL is missing"
And yes, both files are in the same directory. And I tested to include ".env" as parameter in the createImmutable. Both as string and array. Some two days ago, without any change has been working without any problem.
I copy-pasted the lines for createImmutable and the load(), and I copy-pasted the variable.
And fail in differents servers, but with both having 7.4

How can I know in wich paths are searching the file? Maybe that is a clue.

**Comment by marioquartz** [comment]
Ok. I tested more. Changing the ->required() line to be under ->load() There are no exception, but `var_dump(getenv("BASE_URL"));` is `false`.

So my problem remains.

**Comment by GrahamCampbell** [comment]
See https://github.com/vlucas/phpdotenv#putenv-and-getenv. I'd highly recommend changing your call to `getenv` with a lookup in `$_SERVER`.
