### ISSUE TITLE
The environment file is invalid! Failed to parse dotenv file due to an unexpected escape sequence.  Failed at ['C:\PROGRA~1\MariaDB 10.7\bin'].

### ISSUE THREAD

**Issue by escheffler2022** [vlucas/phpdotenv#515]
The environment file is invalid! Failed to parse dotenv file due to an unexpected escape sequence.  Failed at ['C:\PROGRA~1\MariaDB 10.7\bin'].
I am trying to create a brand new installation of SNIPE-IT on a Windows 2019 Datacenter server.  The original installation is not working, so I did a backup of the old database which I would like to restore on the new installation.  When I try to do the upgrade.php, at Step 2: Backing up database: 
The environment file is invalid! Failed to parse dotenv file due to an unexpected escape sequence.  Failed at ['C:\PROGRA~1\MariaDB 10.7\bin'].
It happens through almost each of the steps after that.

**Comment by GrahamCampbell** [comment]
This is happening because you have invalid syntax in your file.
