### ISSUE TITLE
Documentation should include an example of multiline strings

### ISSUE THREAD

**Issue by Azeirah** [vlucas/phpdotenv#518]
Laravel uses this package, their passport docs state you can save a PEM key in .env. This is true, but their formatting is wrong. I'm updating their documentation to document it correctly, but would like to refer to an official source that this is how the formatting is supposed to be done.

Wrong formatting

```
MY_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----
line1
line2
line3
----END PRIVATE KEY-----"
```

Correct formatting

```
MY_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nline1\nline2\nline3\n----END PRIVATE KEY-----"
```

See the docs for [version 8](https://laravel.com/docs/8.x/passport#loading-keys-from-the-environment) or [version 9](https://laravel.com/docs/9.x/passport#loading-keys-from-the-environment) for Laravel, neither mention the right multiline string formatting.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch, but that's not correct, actually. You can put real newlines in your strings. We have tests that verify this works: https://github.com/vlucas/phpdotenv/blob/master/tests/fixtures/env/multiline.env, https://github.com/vlucas/phpdotenv/blob/b83be80cedb862eeb030370cd7939f8333b1c496/tests/Dotenv/DotenvTest.php#L320-L330

**Comment by GrahamCampbell** [comment]
Please consider our tests as the official source.

**Comment by Azeirah** [comment]
Very strange, what could have been the issue with my .env file then? I replaced all newlines with the literal \n character. Before it didn't work, after it did. Might it be an issue with openssl_pkey_get_private/openssl_pkey_get_public instead?

**Comment by GrahamCampbell** [comment]
Not sure. You can try dumping the config values to see what they ended up as.
