### ISSUE TITLE
Encountered unexpected whitespace at [my repos]

### ISSUE THREAD

**Issue by bellash13** [vlucas/phpdotenv#520]
When the project directory contains whitespace 
`$dotenv = Dotenv::createImmutable(__DIR__,'.env');` will not work. Here is the error 

Uncaught Dotenv\Exception\InvalidFileException: Failed to parse dotenv file. Encountered unexpected whitespace at [my repos]. in `..\vendor\vlucas\phpdotenv\src\Parser\Parser.php:30` Stack trace: #0 `..\vendor\graham-campbell\result-type\src\Error.php(118):`

**Comment by GrahamCampbell** [comment]
That's not what's happening here. You have a syntax error in your .env file itself.

**Comment by bellash13** [comment]
Thank you for this. Inside `.env` file, I could escape from `SAVE_TO=C:/my repos` to `SAVE_TO="C:/my repos"` and now it works perfectly.

This should be closed.
