### ISSUE TITLE
Additional .env files are not loaded

### ISSUE THREAD

**Issue by stepanov** [vlucas/phpdotenv#521]
Hi,

I use .env to store all settings of my project with default or dummy  values. Then for each environment I'd like to override desired values in the .env.local, .env.development and .env.production. The code to load those configs is here:

```php
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__ , ['.env', '.env.local', '.env.development', '.env.production'], true);
$dotenv->safeLoad();
```
As result. the .env is loaded but any others not.
Any suggestion to fix that will be appreciated. I use version 5.3

Regards, Michael

**Comment by GrahamCampbell** [comment]
You need to pass `false` as the 2nd param. Passing `true` means it stops loading as soon as it is found a file.
