### ISSUE TITLE
update the version of jQuery you are using

### ISSUE THREAD

**Issue by SC-Josh** [vlucas/phpdotenv#525]
<img width="804" alt="Screen Shot 2022-06-20 at 12 19 46 PM" src="https://user-images.githubusercontent.com/90015495/174666021-182453c3-360c-46fe-b1b8-2156830f0301.png">

**Comment by GrahamCampbell** [comment]
Nothing to do with us. Please report to phpunit. :)

**Comment by GrahamCampbell** [comment]
In future, please never publically diclose something you think is a security vulnerability. Please follow the security disclosure policy of the repo, which you can find on the Security tab.
