### ISSUE TITLE
Unable to read the "/tmp/build_2f06b5cf/.env" environment file

### ISSUE THREAD

**Issue by heardofdezz** [vlucas/phpdotenv#533]
I updated my composer from v 1 to 2,
my application was running smoothly on heroku without an issue after that update everything locally works perfectly but i cant deploy the  heroku i get this error : 

`!!  PHP Fatal error:  Uncaught Symfony\Component\Dotenv\Exception\PathException: Unable to read the "/tmp/build_2f06b5cf/.env" environment file. in /tmp/build_2f06b5cf/vendor/symfony/dotenv/Dotenv.php:569
       !!  Stack trace:
       !!  #0 /tmp/build_2f06b5cf/vendor/symfony/dotenv/Dotenv.php(92): Symfony\Component\Dotenv\Dotenv->doLoad()
       !!  #1 /tmp/build_2f06b5cf/vendor/symfony/dotenv/Dotenv.php(114): Symfony\Component\Dotenv\Dotenv->load()
       !!  #2 /tmp/build_2f06b5cf/vendor/symfony/dotenv/Dotenv.php(157): Symfony\Component\Dotenv\Dotenv->loadEnv()
       !!  #3 /tmp/build_2f06b5cf/vendor/symfony/runtime/SymfonyRuntime.php(102): Symfony\Component\Dotenv\Dotenv->bootEnv()
       !!  #4 /tmp/build_2f06b5cf/vendor/autoload_runtime.php(23): Symfony\Component\Runtime\SymfonyRuntime->__construct()
       !!  #5 /tmp/build_2f06b5cf/bin/console(11): require_once('...')
       !!  #6 {main}
       !!    thrown in /tmp/build_2f06b5cf/vendor/symfony/dotenv/Dotenv.php on line 569
       !!  `

**Comment by GrahamCampbell** [comment]
This trace is about a different library.
