### ISSUE TITLE
auto_detect_line_endings is deprecated (PHP 8.1 + dotenv v2.6.9)

### ISSUE THREAD

**Issue by schmunk42** [vlucas/phpdotenv#534]
```
PHP Deprecated:  auto_detect_line_endings is deprecated in /app/vendor/vlucas/phpdotenv/src/Loader.php on line 172
```

It's just a warning and code seems to run fine, but a version check might still be considered here.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. This has been fixed in v3. v5 is the latest version, and I'd recommend upgrading ASAP. We are not likely to support PHP 8.2 on v2.
