### ISSUE TITLE
PHP version 7.1 is not supported now

### ISSUE THREAD

**Issue by qpweb** [vlucas/phpdotenv#535]
Depending on phpoption/phpoption 1.9.0, support for php versions lower than 7.2.5 has been removed
https://github.com/schmittjoh/php-option/commit/dc5ff11e274a90cc1c743f66c9ad700ce50db9ab

You can specify max version in phpoption/phpoption 1.8.* ?

**Comment by GrahamCampbell** [comment]
No need. You can still use this on PHP 7.1. You just need to run composer using PHP 7.1 or use the platform options, and it will download the appropriate dependencies for you.

**Comment by GrahamCampbell** [comment]
https://stackoverflow.com/a/54736948/2491184
