### ISSUE TITLE
Fatal error: Uncaught Error: Class "Dotenv\Dotenv" not found in

### ISSUE THREAD

**Issue by RajrupDasid** [vlucas/phpdotenv#548]
Fatal error: Uncaught Error: Class "Dotenv\Dotenv" not found in projectdb.php Stack trace: #0 {main} thrown in

I was following github phpdotenv tutorial 

I am using latest php and latest composer version available
php 8.2.2
composer 2.5.3
on Arch linux

When the problem is expected to solve?

by the way I have tried clearing composer cache and try again? which was mentioned 2 years ago someone faced the issue

**Comment by geoidesic** [comment]
I have this same problem
