### ISSUE TITLE
Question - are there any 'builtin' variables?

### ISSUE THREAD

**Issue by treii28** [vlucas/phpdotenv#550]
You give an example that shows setting a 'BASEDIR' then using it ( ${BASEDIR} ) in other variables. Since the .env file is usually placed in the root of a project or package, is there any means to access some kind of built-in that will tell you the directory/path where the .env is located to automagically set a BASEDIR or ROOTDIR using whatever location the .env file is stored?

**Comment by GrahamCampbell** [comment]
No, there are no built-ins, but there may be variables already set outside of your env file that can be access from it.

**Comment by GrahamCampbell** [comment]
Some that are resolved from $_SERVER: https://www.php.net/manual/en/reserved.variables.server.php.

**Comment by scottw-finao** [comment]
I'd still like to upvote this - it would still be nice to be able to get the directory where the .env file was located in other code after the environment was loaded. (I ran into another situation where this would be useful)

**Comment by justinskolnick** [comment]
You can save the path to a constant and pass it into `Dotenv\Dotenv::createImmutable()`.
