### ISSUE TITLE
php 8.2  function getenv() not set

### ISSUE THREAD

**Issue by luanmarcosfgns** [vlucas/phpdotenv#555]
in last version php8.2.7 the function getenv() no set
example of do env:
BACKUP_1_TYPE="database"
BACKUP_1_USERNAME="root"
BACKUP_1_PASSWORD="root"
BACKUP_1_DATABASE="database"
BACKUP_1_HOST="localhost"
BACKUP_1_GOOGLETOKEN=""
BACKUP_1_GOOGLEFOLDERID="https://drive.google.com/drive"
BACKUP_1_DIRECTORYTO="/home/user/Documentos/dumps/"
BACKUP_2_TYPE="file"
BACKUP_2_GOOGLETOKEN="oo"
BACKUP_2_GOOGLEFOLDERID="09ne"
BACKUP_2_DIRECTORYTO="/home/user/Documentos/dumps/"
BACKUP_2_DIRECTORYFROM="/user/luanmarcos/Documentos/"

**Comment by GrahamCampbell** [comment]
This is correct because `getenv` and `putenv` are generally not good functions to use because they are not thread safe, which can lead to incorrect/insecure behaviour on php-fpm. If you really must use getenv, then you can enable unsafe mode as per the readme.
