### ISSUE TITLE
Is there anyway to use sections created in the .env file?

### ISSUE THREAD

**Issue by MatheusGgit** [vlucas/phpdotenv#563]
I would like to separate some variables in my .env file like this:

```
[SECTION]
VAR=

[SECTION_TWO]
VAR=
```

is there anyway to do this?
Sorry if this is a dumb question, but i found nothing about this

**Comment by GrahamCampbell** [comment]
No this is not supported by the out of the box parser. The closest thing is comments, that use a hash at the start.

**Comment by GrahamCampbell** [comment]
I guess your section syntax is really identical to a comment, so yes, this is supported, and the syntax is `# SECTION`. 🤷

**Comment by MatheusGgit** [comment]
Oh, ok.
Thanks!

**Comment by GrahamCampbell** [comment]
FYI: https://github.com/vlucas/phpdotenv#comments.
