### ISSUE TITLE
 Fatal error: Uncaught Error: Class "Dotenv\Dotenv" not found in

### ISSUE THREAD

**Issue by geoidesic** [vlucas/phpdotenv#564]
Hi,

I tried the installation instructions via composer. It has installed v5.6.0 and this is on PHP 8.3.1.

**Comment by GrahamCampbell** [comment]
What does your code look like? Did you forget to require the composer autoloader?

**Comment by geoidesic** [comment]
Yes. It was that. I was trying to use it before the call to autoload. Tx.
