### ISSUE TITLE
Sudden breaking change between 1.0.8 and 1.0.9 with the {$FOO} syntax for nested variables

### ISSUE THREAD

**Issue by motin** [vlucas/phpdotenv#61]
In 1.0.8, one would specify nested variables as ${FOO}, but in 1.0.9, it is specified as {$FOO}.

Relevant diff: https://github.com/vlucas/phpdotenv/compare/v1.0.8...v1.0.9#diff-9fc34dc20f14743cc88df0c70b48555cL187

This breaks existing set-ups using the ${FOO} style syntax. I have two questions:

1. Why use {$FOO} syntax? It is confusing imo to use something so different from how environment variables are specified in bash (without and [with curly braces in order to protect it from other characters](http://wiki.bash-hackers.org/syntax/pe#simple_usage))
2. Is this library using semantic versioning? I'd like to know what kind of version constraint to put in my composer.json

**Comment by kelvinj** [comment]
@motin are you able to provide a PR? Dotenv v1 should probably now support both variants for BC.

Having 2 ways of doing it is confusing in itself though, and as @vlucas prefers the PHP style I think the upcoming v2 will probably stick with the PHP style.

FWIW v2 also allows multiple loaders, so it will accept a `.env.php` loader to load variables from a PHP file that returns an array. Therefore, the argument to follow bash-style variable interpolation diminishes somewhat.

**Comment by vlucas** [comment]
After thinking about it, I think we should stick with bash-style variable interpolation. This is consistent with defining environment variables everywhere else, and still allows the environment variables to work properly when exported or soruced directly in a bash session.

**Comment by motin** [comment]
> Dotenv v1 should probably now support both variants for BC.

It didn't when I tried. With $FOO set to the string "boo", I ended up with variables like `baz_{$FOO}_zoo` becoming `baz_{boo_zoo`.

> @motin are you able to provide a PR?

Would it be enough to revert the change in https://github.com/vlucas/phpdotenv/compare/v1.0.8...v1.0.9#diff-9fc34dc20f14743cc88df0c70b48555cL187 or was there other bugs with the previous implementation?

> FWIW v2 also allows multiple loaders, so it will accept a .env.php loader to load variables from a PHP file that returns an array. Therefore, the argument to follow bash-style variable interpolation diminishes somewhat.

Sounds good, but I'd suggest that only the php-loader should allow PHP-style variables (and most likely the implementation will not at all be dependent on regex), while remaining bash-style variable interpolation in .env (or .env.sh).

> After thinking about it, I think we should stick with bash-style variable interpolation. This is consistent with defining environment variables everywhere else, and still allows the environment variables to work properly when exported or sourced directly in a bash session.

Great to hear! I'll wait with upgrading until 1.2.0 comes out then (please don't add a new breaking change as minor version 1.1.1 :))

**Comment by kelvinj** [comment]
> It didn't when I tried.

Sorry, I wasn't clear. The bash style was removed and I was saying it should be corrected.

> Would it be enough to revert the change in v1.0.8...v1.0.9#diff-9fc34dc20f14743cc88df0c70b48555cL187 …

I think the implementation changed. It should be enough to update the tests & fix the regex.

**Comment by vlucas** [comment]
In v2.0.0 (tagged just now), it's all bash-style syntax.
