### ISSUE TITLE
v2 Release Prep

### ISSUE THREAD

**Issue by vlucas** [vlucas/phpdotenv#62]
First off -

Thanks everyone (especially @kelvinj) for all the hard work on v2 so far. I just updated the README file for it, as well as made some naming changes to the assertion methods to make them read better. Check the code and/or the README file to see what I mean.

**My concerns before the release:**
Now that we have alternate PHP and JSON loaders, I would like to change the variable nesting to match the bash-style syntax instead of the current PHP-style syntax. I would also like to remove support for spaced values that are not quoted.

The primary motivation for these changes is that I think if you use the bash-style syntax, there shouldn't be any features of phpdotenv that will break bash evaluation of the `.env` file.

For instance, pull down the latest `v2` branch and run:

```
source tests/fixtures/env/nested.env && echo $NVAR4
```

Then run:
```
source tests/fixtures/env/nested.env && echo $NVAR3
```

And:
```
source tests/fixtures/env/commented.env
```

I also had to switch the example to double quotes instead of single quotes for the bash variable interpolation to work - the same thing that happens in PHP too. Perhaps we should also require double quotes? Is that going too far?

**Comment by vlucas** [comment]
ping @GrahamCampbell @stanlemon

**Comment by kelvinj** [comment]
>  I would like to change the variable nesting to match the bash-style syntax instead of the current PHP-style syntax.

That's my preference too.

> I would also like to remove support for spaced values that are not quoted.

> there shouldn't be any features of phpdotenv that will break bash evaluation of the `.env` file.

That's a sensible goal and a reasonable time to make that change.

You'd also need to prevent spaces around the `=` sign.

> Perhaps we should also require double quotes? Is that going too far?

Not if the goal is bash compatibility.

I'm :+1: on all this.

**Comment by stanlemon** [comment]
Sounds great, thanks for your continued work on this project!

**Comment by sagikazarmark** [comment]
Any schedule when the new version will be released?

**Comment by vlucas** [comment]
There is no current timeline - I just want to make sure everything is right before the release.

**Comment by sagikazarmark** [comment]
:+1:

**Comment by vlucas** [comment]
Just updated this today, and am awaiting test results for an initial v2 release.

**Comment by sagikazarmark** [comment]
I am already using v2 with success.

**Comment by vlucas** [comment]
Make sure everything still works with the new stricter rule set on `.env` files ;)

**Comment by sagikazarmark** [comment]
Everything is working fine. I am using simple .env loader with `${NESTED}` variables.

**Comment by vlucas** [comment]
Perfect. It also passed all the tests, so I guess we're ready for an initial release!

**Comment by kelvinj** [comment]
Yay!

I've been running on the latest v2 and all good for me.

**Comment by kelvinj** [comment]
FYI there's not mention in the readme of the `dotenv()` helper method.

**Comment by kelvinj** [comment]
Nor the alternative loaders. :smiley:

**Comment by vlucas** [comment]
Very true. Those should at least be in there with a mention.

**Comment by kelvinj** [comment]
It'd be great to get a v2 out the door and then try and get it into Laravel 5, which I think it being released in beta this week.

Purely selfish… I have a project that I'm upgrading to L5 and I want to use v2 with it, or rather, not have to rework it back into v1. :)

**Comment by GrahamCampbell** [comment]
> It'd be great to get a v2 out the door and then try and get it into Laravel 5

It's too late for 5.0, it'll be going into 5.1. The final 5.0.0 is released tomorrow or the day after if we hit any issues.

**Comment by kelvinj** [comment]
@GrahamCampbell  Gotcha, cheers.

**Comment by GrahamCampbell** [comment]
What's holding the 2.0 release btw? Anything I can help with?

**Comment by sagikazarmark** [comment]
Does that mean release is coming?

**Comment by vlucas** [comment]
It means the release is going to be a bit different - see #77 for info.
