### ISSUE TITLE
Parse line breaks

### ISSUE THREAD

**Issue by b3njamin** [vlucas/phpdotenv#65]
Something like the node.js version
https://github.com/motdotla/dotenv/blob/master/lib/main.js#L31

**Comment by vlucas** [comment]
Sorry, I am not understanding your request. Can you provide some more details, and perhaps a sample `.env` file that doesn't parse right now that you want to be able to be parsed?

**Comment by b3njamin** [comment]
Sorry, essentially I’m asking for \n characters to be parsed as literal new lines.

**Comment by b3njamin** [comment]
``` shell
MULTI_LINE_KEY="awesome\nmultiline\nkey" 
```

```shell
MULTI_LINE_KEY=awesome
multiline
key
```

**Comment by xjchengo** [comment]
If parsing newline, variables may have different values between sourcing it in shell and loading it in php. Maybe you can use [`str_place`](http://php.net/manual/en/function.str-replace.php) to make newlines work.
