### ISSUE TITLE
`null` password

### ISSUE THREAD

**Issue by a-komarev** [vlucas/phpdotenv#71]
I'm using a DB_PASSWORD=null on a test server, and dotenv thinking that my password shouldn't be entered. Is there any way to provide it like a string "null"?

**Comment by vlucas** [comment]
You should be able to just provide an empty string

**Comment by a-komarev** [comment]
My password is 'null', 4 letters :} it's not empty! It's a real password.

**Comment by vlucas** [comment]
Well as far as I know, dotenv is not casting or mucking with any values - all shell variables are strings. Are you using dotenv with something else, like Laravel 5?

**Comment by a-komarev** [comment]
Yep. I'm using it in Laravel 5. I should write about it to them i suppose.

**Comment by vlucas** [comment]
Yes - I believe @taylorotwell wrote some code on top of dotenv to cast all string values that look like types to their respective types ("true", "false", "null", "123", etc.).
