### ISSUE TITLE
Create a smartLoad() method

### ISSUE THREAD

**Issue by rentalhost** [vlucas/phpdotenv#74]
With it, you will not need pass the `.env` directory, it'll transverse back directory until find the first `.env` (like the `jQuery.closest()` does). For instance:

    /home/username/www/path/to/my/bootstrap.php <-- smartLoad() here
    /home/username/.env

`smartLoad()` will transverse directories until find the first accessible `.env` file, or will fail.

    /home/username/www/path/to/my/.env <-- fail
    /home/username/www/path/to/.env <-- fail
    /home/username/www/path/.env <-- fail
    /home/username/www/.env <-- fail
    /home/username/.env <-- found

**Signature:**

    Dotenv::smartLoad(string $startDir = __DIR__, string $filename = ".env")
    :: Can thrown InvalidArgumentException:
    :: Dotenv: Environment file [filename] not found or not readable from [startDir]. 

It'll help a lot because you will not need specifiy two directories to local env and remote env, it'll load file smartly for you or thrown an exception if no `.env` is found.

Alternativaly, just turns `load($path)` optional. If you omit it, it'll transverse from caller path.

**Comment by vlucas** [comment]
I don't want Dotenv to be doing this right now. You should always specify the path to your .env file.
