### ISSUE TITLE
Does not support Chinese characters ?

### ISSUE THREAD

**Issue by moeczt** [vlucas/phpdotenv#75]
I use Laravel5 framework  to  develop
then in .env has
```
APP_NAME="中文"
```
and in config/app.php has
```
'app_name'=>env('APP_NAME', 'app_name')
```
run the code
```
$name = config('app.app_name');
dd($name);
```
print
```
app_name
```

**Comment by jrobeson** [comment]
Please show how to reproduce without Laravel methods. By that i mean, only use the instructions in the README. Laravel specific bugs should be submitted to Laravel.

**Comment by mengzyou** [comment]
I test it with laravel, it works fine for Chinese. 
In the `.env` file:  
> APP_NAME = "应用"  

```php
<?php
require "vendor/autoload.php";

$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->overload();

$appname = getenv('APP_NAME');
echo "$appname";
```

Then it printout **应用** .
