### ISSUE TITLE
What's Blocking The 2.0 Release Please?

### ISSUE THREAD

**Issue by GrahamCampbell** [vlucas/phpdotenv#77]
We were hopping to get phpdotenv 2.x into Laravel 5.1. Is there anything we can do to help out?

**Comment by vlucas** [comment]
I am backing out some of the stricter changes I made so that phpdotenv 2.0 will be able to accept values with single quotes and no quotes at all if there are no spaces in the value. After that, I will do an official release.

**Comment by GrahamCampbell** [comment]
Cool. Is that likely to be done before the end of April, because we're likely to not accept dependency changes in Laravel 5.1 into May.

**Comment by vlucas** [comment]
I am actually doing it right now :)

**Comment by vlucas** [comment]
Changes done - Seeing as how you guys are very experienced staging major releases, what is the best way to go about this?

We currently have a `v2` branch, and at some point, I want to move that to `master` and tag an official v2.0.0 release. Are there any problems with just going ahead and doing that now that everything else (code and README) is ready? Are there any "gotchas" I should know about with composer?

**Comment by GrahamCampbell** [comment]
It's fine to move the code over to the master. I don't know if maintaining 1.1 is something you want to do. If so, make a "1.1" branch, and composer will automatically alias that to 1.1.x-dev for you, then you can alias the master to 2.0.x-dev, and everything will work fine. :) Otherwise, you can just maintain a single master branch, aliased to 2.0.x-dev. All the 1.x releases will still be available due to the tags either way. :)

**Comment by GrahamCampbell** [comment]
Tagging a 1.1.1 release before moving v2 to the master might be a good idea too. :)

**Comment by GrahamCampbell** [comment]
Ping. :)

**Comment by GrahamCampbell** [comment]
Ping @vlucas.

**Comment by GrahamCampbell** [comment]
Ping @vlucas. Laravel 5.1 needs to ship in the next few days. :)

**Comment by mamchenkov** [comment]
@GrahamCampbell you might consider an alternative - [josegonzalez/php-dotenv](https://github.com/josegonzalez/php-dotenv/).  ;)

**Comment by vlucas** [comment]
I have not abandoned this - just hesitant to push this out as 2.0 right now. I ran into some issues with the current Variable class architecture that I am not 100% happy with. I am also thinking I don't want to commit to supporting JSON and PHP loaders (currently in 2.0 branch), so I can keep this project very simple and shell-style only.

I will probably end up creating a new 2.0 branch that basically just updates phpdotenv to an instantiated object (non-static) with a proper PSR-4 namespaced loader with some re-vamped require checks, and then move some of the current stuff to a 2.1 release.

**Comment by GrahamCampbell** [comment]
Works for me. :)

**Comment by GrahamCampbell** [comment]
Is 1.x being maintained for a long period of time then?

**Comment by sagikazarmark** [comment]
@mamchenkov Suggesting another package in a package's issue is not very nice.

Since 2.0 is coming up I think it is safe to create a 1.x branch for version 1.x and move v2 to master as @GrahamCampbell. Even if you are not releasing right now. You can also tag pre-releases if you are not entirely happy with the current code and want to give a preview of the current state of the package. This way people can start to use it.

**Comment by tuupola** [comment]
Personally I think ditching json etc is a good idea. Environment is environment and those who understand why will use it. There already are gazillion of general config managers.

**Comment by sagikazarmark** [comment]
:+1:

**Comment by vlucas** [comment]
Yep. That's the main motivation behind it - way too many people are thinking this is a general config replacement, asking for things like array support, etc. This is sensitive config values only, not a full config replacement, and since it emulates Environment variables, it should only support setting variables the same way the shell does. Adding JSON, PHP, and YAML loaders will just confuse more people, and is beyond the scope of this library.

**Comment by GrahamCampbell** [comment]
Is it possible to get 2.0.0 out today so laravel 5.1 can switch to it?

**Comment by vlucas** [comment]
With my current idea for a 2.0, that should be possible. I am working on it now and will try my best!

**Comment by GrahamCampbell** [comment]
Great. :)

**Comment by GrahamCampbell** [comment]
"1.1" is a better branch name than "1.x" because composer will automatically understand it as being "1.1.x-dev".

**Comment by vlucas** [comment]
Just submitted PR #87 for community review. Will update the comments on it shortly.

**Comment by vlucas** [comment]
@GrahamCampbell deleted the 1.x branch and re-named it 1.1 :)

**Comment by GrahamCampbell** [comment]
It also might make sense to keep "2.0" as a "2.0" branch, and have the master aliased to "2.1". Laravel and symfony follow this approach. :)

**Comment by vlucas** [comment]
Okay. Good advice. I am still waiting on the results from Travis-CI, and I am going to be busy tonight. I will give this 24 hours for other comments from the community who are following this tickets, and then will publish a 2.0 tagged release tomorrow morning.

**Comment by GrahamCampbell** [comment]
Ok. Sounds great. :)

**Comment by vlucas** [comment]
v2.0.0 has been tagged in a release: https://packagist.org/packages/vlucas/phpdotenv

:fireworks: :100:
