### ISSUE TITLE
Feature request: makeMutable($variable)

### ISSUE THREAD

**Issue by schmunk42** [vlucas/phpdotenv#78]
Would be nice if we could make just a single ENV var mutable.

My use case would be to prefix a database name stored in ENV, because I don't want to override all my variables from `.env` I can't just `makeMutable()`.

**Comment by xjchengo** [comment]
Why not separating mutable and immutable variables and putting them in seperate files? Then you can use load method to load immutable variables and overload method to load mutable variables. In this way, your collaborator can know which variables are immutable better.

**Comment by GrahamCampbell** [comment]
https://github.com/vlucas/phpdotenv/issues/76#issuecomment-167806230

**Comment by GrahamCampbell** [comment]
I would not recommend using phpdotenv in this way.
