### ISSUE TITLE
[Proposal] make nested variables can be escaped

### ISSUE THREAD

**Issue by xjchengo** [vlucas/phpdotenv#80]
Now in phpdotenv v2, if i use a nonexistent variable in nesting, the variable will not be resolved. This behavior is kind of strange because if i source the file, the nested variable will be resolved as a empty value. 

```bash
TEST="${NONEXIST}variable" 
``` 

If I source above file, `TEST` will be `variable`. But if i load above file using phpdotenv, `$_ENV['TEST']` will be `${NONEXIST}variable`.

```bash
EXIST="existent"
TEST="\${EXIST}variable" 
``` 

If I source above file, `TEST` will be `${EXIST}variable`. But if i load above file, `$_ENV['TEST']` will be `\existentvariable`.

So i think $ should be able to escaped by prefixing with backslash and if not escaped, nonexistent variable should be resolve as empty value.

If the feature is acceptable, I can send a pull request.

**Comment by vlucas** [comment]
I agree that this should be able to be escaped. I will definitely accept a PR to the `v2` branch. I am about to do a v2.0.0 release, so get it in fast! ;)

**Comment by xjchengo** [comment]
ok, i will send a PR today.

**Comment by xjchengo** [comment]
I have send a PR. With regard to nested variables, I have following thoughts:

- remove nested variable support in JSON format

  JSON standard doesn't support nested variable. JSON is used primarily to transmit data between a server and web application. If I use a nested variable in JSON, I cannot use it in other place. For example, I cannot directly use a json config with nested variable in a project without phpdotenv package. And the nested variables in json file is a little confusing.

- use built-in variable parsing in php format

  Current nested variables in php config make it unexchangeable between differnt php projects. Because not all projects support this variable type. So I recommand using following way instead:
```php
$baseDir="/var/webroot/project-root";
$cacheDir="${baseDir}/cache";
$tempDir="${baseDir}/tmp";
return array(
    'BASE_DIR' => $baseDir,
    'CACHE_DIR' => $cacheDir,
    'TMP_DIR' => $tmpDir,
);
```

- make .env loader result as close as to shell parser result

**Comment by vlucas** [comment]
The new v2.0.0 release dropped the JSON and PHP loaders to standardize on shell-style only, which was the whole intent of this project in the first place. Please re-submit your changes based on the new v2.0.0 code, and we can review it for merge. Thanks!

**Comment by xjchengo** [comment]
V2 finally released. I will send a pull request today.
