### ISSUE TITLE
Drop PHP 5.3 Support In 2.1

### ISSUE THREAD

**Issue by GrahamCampbell** [vlucas/phpdotenv#92]
What do you say?

**Comment by vlucas** [comment]
There is no real need to (which is the only reason I didn't in 2.0.0), but 5.3 is deprecated and no longer receiving updates, so it does make sense to drop it from 2.1.0.

**Comment by xjchengo** [comment]
If dropping php 5.3 support, major version should bump to follow semantic versioning.

**Comment by GrahamCampbell** [comment]
That depends if we're following semver or not.

**Comment by huglester** [comment]
Probably best was to drop it's support when jumping to 2.0. but now it's too late :(

**Comment by GrahamCampbell** [comment]
That's what I wanted. :(

**Comment by GrahamCampbell** [comment]
> but 5.3 is deprecated and no longer 

That was true when we released 2.0.0 too @vlucas.

**Comment by vlucas** [comment]
We can't do this if we want to follow semver, so we're stuck with it now. Fortunately, this library doesn't really do anything fancy, so it's fine.
