### ISSUE TITLE
[Proposal] assign a exception code to every exception

### ISSUE THREAD

**Issue by xjchengo** [vlucas/phpdotenv#94]
Now many InvalidArgumentException can be thrown by different reasons. It is hard to distinguish them.

**Comment by GrahamCampbell** [comment]
> exception code

:-1:

**Comment by GrahamCampbell** [comment]
:+1: for us having our own exception classes.

**Comment by xjchengo** [comment]
Yes, having own exception calsses is better way. Is this feature underway?

**Comment by GrahamCampbell** [comment]
> Is this feature underway?

No. Feel free to take it on. :)

**Comment by xjchengo** [comment]
Ok.
